_target = sideUnknown;
_restrictionDistance = 15;
_specNames = ["排長","前線火炮觀察員","醫護兵","班長","伍長","步槍兵","步槍兵(反坦克)","自動步槍兵","輔助助手","工程兵","精準射手","排用機槍兵","發射器專精兵","火砲操作人員","狙擊組","直升機組員","機組員","飛行員"];
_specSlots = [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90];
_specTypes = [
	["I_officer_F"],
	["I_soldier_UAV_06_F"],
	["I_medic_F"],
	["I_Soldier_SL_F"],
	["I_Soldier_TL_F"],
	["I_Soldier_F"],
	["I_soldier_LAT_F"],
	["I_soldier_AR_F"],
	["I_soldier_AAR_F","I_soldier_AAT_F","I_Soldier_A_F"],
	[""],
	["I_soldier_M_F"],
	["I_support_MG_F"],
	["I_soldier_AT_F"],
	["I_support_Mort_F","I_support_AMort_F"],
	["I_spotter_F","I_sniper_F"],
	["I_Helipilot_F","I_helicrew_F"],
	["I_crew_F"],
	["I_Pilot_F"]	
];

_generalItems = [
"ACE_SpareBarrel",
"ACE_CableTie",
"ACE_UAVBattery",
"rhs_weap_savz58p",
"rhs_weap_savz58p_black",
"rhs_weap_savz58v",
"rhs_weap_savz58v_black",
"rhs_weap_6p53",
"rhs_30Rnd_762x39mm_Savz58",
"rhs_18rnd_9x21mm_7N28",
"rhsgref_uniform_woodland",
"rhssaf_vest_md99_woodland_rifleman_radio",
"rhssaf_vest_md99_woodland_rifleman",
"rhssaf_vest_md99_md2camo_rifleman_radio",
"rhssaf_vest_md99_md2camo_rifleman",
"rhsgref_wdl_alicepack",
"UK3CB_B_Largepack",
"UK3CB_UN_B_B_ASS",
"UK3CB_B_Fieldpack",
"UK3CB_CHC_C_B_HIKER",
"UK3CB_B_Alice_K",
"rhsgref_helmet_M1_painted_alt01",
"rhsgref_helmet_M1_painted",
"rhsgref_helmet_m1942_alt1",
"rhssaf_helmet_m97_md2camo",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemRadio",
"ItemGPS",
"rhssaf_zrak_rd7j",
"ACE_splint",
"ACE_fieldDressing",
"ACE_bodyBag",
"ToolKit",
"ACE_RangeCard",
"ACE_DefusalKit",
"ACE_artilleryTable",
"ACE_rope12",
"ACE_rope15",
"ACE_rope18",
"ACE_rope27",
"ACE_rope36",
"ACE_EarPlugs",
"ACE_tourniquet",
"ACRE_PRC148",
"ACRE_PRC152",
"ACRE_PRC343",
"ACE_EntrenchingTool",
"ACE_Flashlight_MX991",
"ACE_Flashlight_XL50",
"ACE_morphine",
"ACE_wirecutter",
"ACE_MapTools",
"I_IR_Grenade",
"ACE_Chemlight_UltraHiOrange",
"ACE_Chemlight_HiGreen",
"ACE_Chemlight_HiBlue",
"ACE_Chemlight_Orange",
"ACE_Chemlight_White",
"ACE_Chemlight_IR",
"ACE_Chemlight_HiWhite",
"ACE_Chemlight_HiRed",
"ACE_Chemlight_HiYellow",
"Chemlight_red",
"Chemlight_green",
"Chemlight_blue",
"Chemlight_yellow",
"ACE_M14",
"rhs_mag_an_m14_th3",
"rhs_mag_an_m8hc",
"ACE_M84",
"rhs_mag_mk84",
"rhs_mag_m7a3_cs",
"HandGrenade",
"rhs_mag_m18_green",
"rhs_mag_m18_purple",
"rhs_mag_m18_red",
"rhs_mag_m18_yellow"];

_CoItems = ["rhs_pdu4",
"CUP_hgun_FlareGun",
"CUP_FlareWhite_265_M",
"CUP_FlareRed_265_M",
"CUP_FlareGreen_265_M",
"CUP_FlareYellow_265_M",
"CUP_IllumFlareWhite_265_M",
"CUP_IllumFlareRed_265_M",
"CUP_IllumFlareGreen_265_M",
"CUP_IllumFlareYellow_265_M",
"CUP_StarClusterWhite_265_M",
"CUP_StarClusterRed_265_M",
"CUP_StarClusterGreen_265_M",
"CUP_StarClusterYellow_265_M",
"rhs_weap_m79",
"1Rnd_HE_Grenade_shell",
"UGL_FlareWhite_F",
"UGL_FlareGreen_F",
"UGL_FlareRed_F",
"UGL_FlareYellow_F",
"UGL_FlareCIR_F",
"ACE_40mm_Flare_white",
"ACE_40mm_Flare_red",
"ACE_40mm_Flare_green",
"ACE_40mm_Flare_ir",
"1Rnd_Smoke_Grenade_shell",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_SmokeGreen_Grenade_shell",
"1Rnd_SmokeYellow_Grenade_shell",
"1Rnd_SmokePurple_Grenade_shell",
"1Rnd_SmokeBlue_Grenade_shell",
"1Rnd_SmokeOrange_Grenade_shell",
"ACE_MX2A"] + _generalItems;
_FACItems = [
"UK3CB_B_I_Alice_Radio_Backpack",
"ACE_MX2A",
"Laserdesignator",
"I_UAV_01_backpack_F",
"I_UavTerminal",
"CUP_LRTV",
"Laserbatteries"] + _generalItems;
_MItems = [
"ACE_surgicalKit",
"ACE_adenosine",
"ACE_bloodIV_250",
"ACE_bloodIV",
"ACE_tourniquet",
"ACE_fieldDressing",
"ACE_morphine",
"ACE_epinephrine",
"ACE_bloodIV_500",
"ACE_quikclot",
"ACE_packingBandage",
"ACE_elasticBandage",
"ACE_personalAidKit",
"B_Kitbag_rgr"] + _generalItems;
_SLItems = [
"CUP_hgun_FlareGun",
"CUP_FlareWhite_265_M",
"CUP_FlareRed_265_M",
"CUP_FlareGreen_265_M",
"CUP_FlareYellow_265_M",
"CUP_IllumFlareWhite_265_M",
"CUP_IllumFlareRed_265_M",
"CUP_IllumFlareGreen_265_M",
"CUP_IllumFlareYellow_265_M",
"CUP_StarClusterWhite_265_M",
"CUP_StarClusterRed_265_M",
"CUP_StarClusterGreen_265_M",
"CUP_StarClusterYellow_265_M",
"rhs_weap_m79",
"1Rnd_HE_Grenade_shell",
"UGL_FlareWhite_F",
"UGL_FlareGreen_F",
"UGL_FlareRed_F",
"UGL_FlareYellow_F",
"UGL_FlareCIR_F",
"1Rnd_Smoke_Grenade_shell",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_SmokeGreen_Grenade_shell",
"1Rnd_SmokeYellow_Grenade_shell",
"1Rnd_SmokePurple_Grenade_shell",
"1Rnd_SmokeBlue_Grenade_shell",
"1Rnd_SmokeOrange_Grenade_shell",
"ACE_MX2A"] + _generalItems;
_FTLItems = [
"rhs_pdu4",
"rhs_weap_m79",
"1Rnd_HE_Grenade_shell",
"UGL_FlareWhite_F",
"UGL_FlareGreen_F",
"UGL_FlareRed_F",
"UGL_FlareYellow_F",
"UGL_FlareCIR_F",
"1Rnd_Smoke_Grenade_shell",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_SmokeGreen_Grenade_shell",
"1Rnd_SmokeYellow_Grenade_shell",
"1Rnd_SmokePurple_Grenade_shell",
"1Rnd_SmokeBlue_Grenade_shell",
"1Rnd_SmokeOrange_Grenade_shell",
"ACE_MX2A"] + _generalItems;
_RItems = [
"rhs_weap_rpg26"] + _generalItems;
_RLATItems = [
"rhs_weap_rpg7",
"rhs_rpg7_PG7VL_mag",
"rhs_rpg7_PG7V_mag",
"rhs_rpg7_PG7VM_mag",
"rhs_rpg7_PG7VS_mag",
"rhs_rpg7_PG7VR_mag",
"rhs_rpg7_OG7V_mag",
"rhs_rpg7_TBG7V_mag"] + _generalItems;
_ARItems = [
"CUP_arifle_Sa58_Klec",
"CUP_45Rnd_Sa58_M",
"CUP_45Rnd_Sa58_M_TracerG"] + _generalItems;
_ENGItems = [
"ACE_Clacker",
"ACE_M26_Clacker",
"ACE_DefusalKit",
"DemoCharge_Remote_Mag",
"SatchelCharge_Remote_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"APERSBoundingMine_Range_Mag",
"SLAMDirectionalMine_Wire_Mag",
"APERSMine_Range_Mag",
"APERSTripMine_Wire_Mag",
"ACE_VMH3",
"rhs_mine_ozm72_a_mag",
"rhs_mine_ozm72_b_mag",
"rhs_mine_ozm72_c_mag",
"rhs_mag_mine_pfm1",
"rhssaf_mine_pma3_mag",
"rhs_mine_msk40p_blue_mag",
"rhs_mine_msk40p_green_mag",
"rhs_mine_msk40p_red_mag",
"rhs_mine_msk40p_white_mag",
"rhs_mine_pmn2_mag",
"rhs_mag_mine_ptm1",
"CUP_PipeBomb_M",
"rhs_mine_sm320_green_mag",
"rhs_mine_sm320_red_mag",
"rhs_mine_sm320_white_mag",
"APERSMine_Range_Mag",
"ACE_LIB_LadungPM",
"APERSMineDispenser_Mag",
"DemoCharge_Remote_Mag",
"ATMine_Range_Mag",
"SatchelCharge_Remote_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"SLAMDirectionalMine_Wire_Mag",
"APERSMine_Range_Mag",
"APERSBoundingMine_Range_Mag",
"ACE_VMM3"] + _generalItems;
_MKItems = [
"rhs_pdu4",
"ACE_RangeCard",
"rhs_weap_m76",
"rhsgref_10Rnd_792x57_m76",
"CUP_optic_PSO_1_1_open",
"CUP_optic_PSO_1_1",
"rhs_acc_pso1m2",
"rhs_acc_pso1m21",
"CUP_srifle_Mosin_Nagant",
"CUP_srifle_LeeEnfield",
"rhs_acc_pso1m21",
"CUP_optic_PEM",
"CUP_optic_no23mk2",
"CUP_5Rnd_762x54_Mosin_M",
"CUP_10x_303_M"] + _generalItems;
_MGItems = [
"CUP_lmg_UK59",
"rhs_weap_m84",
"CUP_50Rnd_UK59_762x54R_Tracer",
"rhs_100Rnd_762x54mmR",
"rhs_100Rnd_762x54mmR_green",
"rhssaf_250Rnd_762x54R",
"ace_csw_staticM2ShieldCarry",
"ace_csw_m3CarryTripod",
"ace_csw_m3CarryTripodLow",
"ace_compat_rhs_usf3_mk19_carry",
"ace_csw_m3CarryTripodLow",
"ace_csw_m3CarryTripod",
"ace_csw_100Rnd_127x99_mag_yellow",
"ace_csw_100Rnd_127x99_mag",
"ace_compat_rhs_usf3_48Rnd_40mm_MK19",
"ace_compat_rhs_usf3_48Rnd_40mm_MK19_M430A1",
"ace_compat_rhs_usf3_48Rnd_40mm_MK19_M1001"] + _generalItems;
_MATItems = [
"rhs_weap_igla",
"CUP_launch_Metis",
"CUP_launch_BF3_Loaded",
"rhs_mag_9k38_rocket",
"CUP_AT13_M",
"Vorona_HEAT",
"Vorona_HE",
"CUP_PTFHC_M",
"CUP_PTFHE_M",
"CUP_PTF3IT_M"] + _generalItems;
_MTRItems = [
"RHS_Podnos_Bipod_Bag",
"ACE_1Rnd_82mm_Mo_HE",
"ACE_1Rnd_82mm_Mo_Illum",
"ACE_1Rnd_82mm_Mo_Smoke",
"RHS_Podnos_Gun_Bag"] + _generalItems;
_SPItems = [
"rhs_pdu4",
"ACE_RangeCard",
"CUP_srifle_ksvk",
"UK3CB_SVD_OLD",
"CUP_srifle_Mosin_Nagant",
"CUP_srifle_LeeEnfield",
"rhs_acc_pso1m21",
"CUP_optic_PSO_3",
"CUP_optic_PEM",
"CUP_optic_no23mk2",
"rhs_10Rnd_762x54mmR_7N1",
"CUP_5Rnd_762x54_Mosin_M",
"CUP_10x_303_M",
"CUP_5Rnd_127x108_KSVK_M",
"ACE_Tripod",
"Laserdesignator",
"Laserbatteries",
"ACE_Kestrel4500",
"ACE_SpottingScope",
"U_I_FullGhillie_ard",
"U_I_FullGhillie_sard",
"U_I_FullGhillie_lsh",
"optic_LRPS",
"U_I_GhillieSuit"] + _generalItems;
_HPItems = [
"U_I_HeliPilotCoveralls",
"H_PilotHelmetHeli_I",
"SMG_02_F",
"SMG_03C_black",
"SMG_03C_camo",
"SMG_03C_TR_black",
"SMG_03C_TR_camo",
"SMG_01_F",
"30Rnd_45ACP_Mag_SMG_01",
"30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow",
"50Rnd_570x28_SMG_03",
"CUP_50Rnd_570x28_Yellow_Tracer_P90_M",
"30Rnd_9x21_Mag_SMG_02",
"CUP_30Rnd_9x19_EVO"] + _generalItems;
_VItems = [
"UK3CB_HK33KA3",
"UK3CB_HK33_30rnd_556x45",
"UK3CB_AAF_O_V_Eagle_CREW_DIGI_GRN",
"H_HelmetCrew_I",
"ToolKit"] + _generalItems;
_FYItems = [
"U_I_pilotCoveralls",
"H_PilotHelmetFighter_I",
"SMG_02_F",
"SMG_03C_black",
"SMG_03C_camo",
"SMG_03C_TR_black",
"SMG_03C_TR_camo",
"SMG_01_F",
"30Rnd_45ACP_Mag_SMG_01",
"30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow",
"50Rnd_570x28_SMG_03",
"CUP_50Rnd_570x28_Yellow_Tracer_P90_M",
"30Rnd_9x21_Mag_SMG_02",
"CUP_30Rnd_9x19_EVO",
"ToolKit"] + _generalItems;


_specItems = [_CoItems, _FACItems, _MItems, _SLItems, _FTLItems, _RItems, _RLATItems, _ARItems, _AARItems, _ENGItems, _MKItems, _MGItems, _MATItems, _MTRItems, _SPItems, _HPItems, _VItems, _FYItems];

//////////////////////////////////////////////////////////////////////////////////////////////

[_target, [_this select 0, _restrictionDistance, _specNames, _specSlots, _specTypes, _specItems]] spawn CHSA_fnc_executeLocalArsenal;