_target = sideUnknown;
_restrictionDistance = 15;
_specNames = ["排長","前線火炮觀察員","醫護兵","班長","伍長","步槍兵","步槍兵(反坦克)","自動步槍兵","輔助助手","工程兵","精準射手","排用機槍兵","發射器專精兵","火砲操作人員","狙擊組","直升機組員","機組員","飛行員"];
_specSlots = [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90];
_specTypes = [
	["I_officer_F"],
	["I_soldier_UAV_06_F"],
	["I_medic_F"],
	["I_Soldier_SL_F"],
	["I_Soldier_TL_F"],
	["I_Soldier_F"],
	["I_soldier_LAT_F"],
	["I_soldier_AR_F"],
	["I_soldier_AAR_F","I_soldier_AAT_F","I_Soldier_A_F"],
	[""],
	["I_soldier_M_F"],
	["I_support_MG_F"],
	["I_soldier_AT_F"],
	["I_support_Mort_F","I_support_AMort_F"],
	["I_spotter_F","I_sniper_F"],
	["I_Helipilot_F","I_helicrew_F"],
	["I_crew_F"],
	["I_Pilot_F"]	
];

_generalItems = [
"rhs_1PN138",
"ACE_SpareBarrel",
"ACE_CableTie",
"ACE_UAVBattery",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemRadio",
"ItemGPS",
"ACE_splint",
"ACE_fieldDressing",
"ACE_bodyBag",
"ToolKit",
"ACE_RangeCard",
"ACE_DefusalKit",
"ACE_artilleryTable",
"ACE_rope12",
"ACE_rope15",
"ACE_rope18",
"ACE_rope27",
"ACE_rope36",
"ACE_EarPlugs",
"ACE_tourniquet",
"ACRE_PRC148",
"ACRE_PRC152",
"ACRE_PRC343",
"ACE_EntrenchingTool",
"ACE_Flashlight_MX991",
"ACE_Flashlight_XL50",
"ACE_morphine",
"ACE_wirecutter",
"ACE_MapTools",
"I_IR_Grenade",
"ACE_Chemlight_UltraHiOrange",
"ACE_Chemlight_HiGreen",
"ACE_Chemlight_HiBlue",
"ACE_Chemlight_Orange",
"ACE_Chemlight_White",
"ACE_Chemlight_IR",
"ACE_Chemlight_HiWhite",
"ACE_Chemlight_HiRed",
"ACE_Chemlight_HiYellow",
"Chemlight_red",
"Chemlight_green",
"Chemlight_blue",
"Chemlight_yellow",
"ACE_M14",
"ACE_Chemlight_UltraHiOrange",
"ACE_Chemlight_HiGreen",
"ACE_Chemlight_HiBlue",
"ACE_Chemlight_Orange",
"ACE_Chemlight_White",
"ACE_Chemlight_IR",
"ACE_Chemlight_HiWhite",
"ACE_Chemlight_HiRed",
"ACE_Chemlight_HiYellow",
"Chemlight_red",
"Chemlight_green",
"Chemlight_blue",
"Chemlight_yellow",
"LIB_F1",
"rhs_mag_f1",
"rhs_mag_nspd",
"rhs_mag_nspn_green",
"rhs_mag_nspn_red",
"rhs_mag_nspn_yellow",
"LIB_RDG",
"rhs_mag_rdg2_black",
"rhs_mag_rdg2_white",
"LIB_Rg42",
"rhs_mag_rgd5",
"CUP_HandGrenade_RGD5",
"Grenade_min_rf_rgd_5",
"rhs_mag_rgn",
"rhs_mag_rgo",
"CUP_HandGrenade_RGO",
"rhs_mag_zarya2",
"MiniGrenade",
"vme_pla_qbz95_1",
"VME_QBZ95_1_30Rnd_DBP87",
"VME_QBZ95_laser_IR_flashlight",
"vme_pla_qsz92",
"vme_pla_qsw06",
"VME_QSZ92_20Rnd_DAP92",
"VME_QSW06_20Rnd_DCV05",
"PLA_CombatUniform_SBCB",
"PLA_B04_RF",
"PLA_T15Vest_RF",
"VME_PLA_Helmet",
"PLAAF_CarryAll_Base",
"PLA_AssaultPack_Fix",
"Binocular"];

_CoItems = ["rhs_pdu4",
"PLA_CombatUniform_SW",
"vme_pla_qbz95_1GL",
"VME_1Rnd_HE_GL",
"VME_1Rnd_Smoke_GL",
"UGL_FlareWhite_F",
"UGL_FlareGreen_F",
"UGL_FlareRed_F",
"UGL_FlareYellow_F",
"UGL_FlareCIR_F",
"1Rnd_Smoke_Grenade_shell",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_SmokeGreen_Grenade_shell",
"1Rnd_SmokeYellow_Grenade_shell",
"1Rnd_SmokePurple_Grenade_shell",
"ACE_MX2A"] + _generalItems;
_FACItems = [
"ACE_MX2A",
"Laserdesignator",
"PLA_UAV_backpack",
"PLA_UavTerminal",
"rhs_pdu4",
"Laserbatteries"] + _generalItems;
_MItems = [
"ACE_surgicalKit",
"ACE_adenosine",
"ACE_bloodIV_250",
"ACE_bloodIV",
"ACE_tourniquet",
"ACE_fieldDressing",
"ACE_morphine",
"ACE_epinephrine",
"ACE_bloodIV_500",
"ACE_quikclot",
"ACE_packingBandage",
"ACE_elasticBandage",
"ACE_personalAidKit",
"B_Kitbag_rgr"] + _generalItems;
_SLItems = [
"PLA_CombatUniform_SW",
"vme_pla_qbz95_1GL",
"VME_1Rnd_HE_GL",
"VME_1Rnd_Smoke_GL",
"1Rnd_HE_Grenade_shell",
"UGL_FlareWhite_F",
"UGL_FlareGreen_F",
"UGL_FlareRed_F",
"UGL_FlareYellow_F",
"UGL_FlareCIR_F",
"1Rnd_Smoke_Grenade_shell",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_SmokeGreen_Grenade_shell",
"1Rnd_SmokeYellow_Grenade_shell",
"1Rnd_SmokePurple_Grenade_shell",
"1Rnd_SmokeBlue_Grenade_shell",
"1Rnd_SmokeOrange_Grenade_shell",
"rhs_pdu4",
"ACE_MX2A"] + _generalItems;
_FTLItems = [
"rhs_pdu4",
"PLA_CombatUniform_SW",
"vme_pla_qbz95_1GL",
"VME_1Rnd_HE_GL",
"VME_1Rnd_Smoke_GL",
"1Rnd_HE_Grenade_shell",
"UGL_FlareWhite_F",
"UGL_FlareGreen_F",
"UGL_FlareRed_F",
"UGL_FlareYellow_F",
"UGL_FlareCIR_F",
"1Rnd_Smoke_Grenade_shell",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_SmokeGreen_Grenade_shell",
"1Rnd_SmokeYellow_Grenade_shell",
"1Rnd_SmokePurple_Grenade_shell",
"1Rnd_SmokeBlue_Grenade_shell",
"1Rnd_SmokeOrange_Grenade_shell",
"ACE_MX2A"] + _generalItems;
_RItems = [
"vme_pla_PF98_AT_Rocket",
"vme_pla_PF98_MP_Rocket",
"VME_QJY88_200Rnd_DVP88_Heavy",
"VME_QJY88_200Rnd_DBP10",
"VME_QJY88_200Rnd_DBP10_Tracer_Green",
"VME_QJY88_200Rnd_DBP10_Red"
] + _generalItems;
_RLATItems = [
"vme_pla_PF89_Rocket",
"vme_pla_PF89A_AST",
"vme_pla_PF89A",
"vme_pla_PF89B",
"vme_pla_PF98",
"vme_pla_PF98_AT_Rocket",
"vme_pla_PF98_MP_Rocket",
"VME_PF98_Scope_FCS",
"vme_pla_WPF89_2"] + _generalItems;
_ARItems = [
"PLA_B04_MG",
"vme_pla_qjb95_1",
"VME_PLA_QJY88",
"VME_QJY88_200Rnd_DVP88_Heavy",
"VME_QJY88_200Rnd_DBP10",
"VME_QJY88_200Rnd_DBP10_Tracer_Green",
"VME_QJY88_200Rnd_DBP10_Red",
"VME_QJB95_1_bipod",
"VME_QJB95_1_75Rnd_DBP87",
"VME_QJB95_1_75Rnd_DBP10_Tracer_Green"] + _generalItems;
_ENGItems = [
"vme_pla_qbz95B_1",
"vme_pla_qcw05",
"VME_QCW05_50Rnd_DCV05",
"VME_QCW05_50Rnd_DAP92",
"ACE_Clacker",
"ACE_M26_Clacker",
"ACE_DefusalKit",
"DemoCharge_Remote_Mag",
"SatchelCharge_Remote_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"APERSBoundingMine_Range_Mag",
"SLAMDirectionalMine_Wire_Mag",
"APERSMine_Range_Mag",
"APERSTripMine_Wire_Mag",
"ACE_VMH3",
"rhs_mine_ozm72_a_mag",
"rhs_mine_ozm72_b_mag",
"rhs_mine_ozm72_c_mag",
"rhs_mag_mine_pfm1",
"rhssaf_mine_pma3_mag",
"rhs_mine_msk40p_blue_mag",
"rhs_mine_msk40p_green_mag",
"rhs_mine_msk40p_red_mag",
"rhs_mine_msk40p_white_mag",
"rhs_mine_pmn2_mag",
"rhs_mag_mine_ptm1",
"CUP_PipeBomb_M",
"rhs_mine_sm320_green_mag",
"rhs_mine_sm320_red_mag",
"rhs_mine_sm320_white_mag",
"APERSMine_Range_Mag",
"ACE_LIB_LadungPM",
"APERSMineDispenser_Mag",
"DemoCharge_Remote_Mag",
"ATMine_Range_Mag",
"SatchelCharge_Remote_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"SLAMDirectionalMine_Wire_Mag",
"APERSMine_Range_Mag",
"APERSBoundingMine_Range_Mag",
"ACE_VMM3"] + _generalItems;
_MKItems = [
"rhs_pdu4",
"ACE_RangeCard",
"vme_pla_qbu88",
"VME_QBU88_10Rnd_DVP88_Sniper",
"VME_95_1_PNV"] + _generalItems;
_MGItems = [
"PLA_B04_MG",
"VME_QJY88_Scope_Light",
"VME_PLA_QJY88",
"VME_QJY88_200Rnd_DVP88_Heavy",
"VME_QJY88_200Rnd_DBP10",
"VME_QJY88_200Rnd_DBP10_Tracer_Green",
"VME_QJY88_200Rnd_DBP10_Red",
"ace_csw_staticM2ShieldCarry",
"ace_csw_m3CarryTripod",
"ace_csw_m3CarryTripodLow",
"ace_compat_rhs_usf3_mk19_carry",
"ace_csw_m3CarryTripodLow",
"ace_csw_m3CarryTripod",
"ace_csw_100Rnd_127x99_mag_yellow",
"ace_csw_100Rnd_127x99_mag",
"ace_compat_rhs_usf3_48Rnd_40mm_MK19",
"ace_compat_rhs_usf3_48Rnd_40mm_MK19_M430A1",
"ace_compat_rhs_usf3_48Rnd_40mm_MK19_M1001"] + _generalItems;
_MATItems = [
"vme_pla_FN6",
"vme_pla_FN6_Rocket",
"vme_pla_HJ12",
"VME_HJ12_AT",
"VME_HJ12_AP"
] + _generalItems;
_MTRItems = [
"RHS_Podnos_Bipod_Bag",
"ACE_1Rnd_82mm_Mo_HE",
"ACE_1Rnd_82mm_Mo_Illum",
"ACE_1Rnd_82mm_Mo_Smoke",
"RHS_Podnos_Gun_Bag"] + _generalItems;
_SPItems = [
"rhs_pdu4",
"VME_QLU11_base",
"optic_QLU11",
"VME_QLU11_4rnd_35mm_HE",
"VME_QLU11_4rnd_35mm_AP",
"ACE_RangeCard",
"VME_QBZ95_1_Silencer",
"vme_pla_LR4",
"VME_LR4_Silencer",
"VME_LR4_5Rnd_M118_Special",
"VME_LR4_5Rnd_M61_AP",
"VME_95_1_PNV",
"VME_M99_Base",
"VME_M99_Suppressor",
"VME_QCW05_Silencer",
"optic_tws",
"VME_LR4_Scope",
"VME_M99_5Rnd_M33_FMJ_Mag",
"VME_M99_5Rnd_M1022_LR_Mag",
"VME_M99_5Rnd_MK263_AP_Mag",
"VME_M99_5Rnd_MK211_HEIAP_Mag",
"vme_pla_qbz95B_1",
"vme_pla_qcw05",
"vme_pla_qcw85",
"VME_QCW05_50Rnd_DCV05",
"VME_QCW05_50Rnd_DAP92",
"VME_QCW85_30Rnd_762x25_Subsonic",
"V_Chestrig_rgr",
"PLA_GhillieSuit_JUNGLEGREEN",
"PLA_GhillieSuit_WD",
"ACE_Tripod",
"Laserdesignator",
"Laserbatteries",
"ACE_Kestrel4500",
"ACE_SpottingScope",
"U_I_FullGhillie_ard",
"U_I_FullGhillie_sard",
"U_I_FullGhillie_lsh",
"optic_LRPS",
"U_I_GhillieSuit"] + _generalItems;
_HPItems = [
"ToolKit",
"PLA_Pilot_Green_Coveralls",
"VME_Pilot_Heli_Helmet",
"vme_pla_qbz95B_1",
"vme_pla_qcw05",
"VME_QCW05_50Rnd_DCV05",
"VME_QCW05_50Rnd_DAP92"] + _generalItems;
_VItems = [
"vme_pla_qbz95B_1",
"vme_pla_qcw05",
"VME_QCW05_50Rnd_DCV05",
"VME_QCW05_50Rnd_DAP92",
"VME_CREW_Cap",
"ToolKit"] + _generalItems;
_FYItems = [
"VME_Pilot_Helmet",
"PLA_Pilot_Green_Coveralls",
"vme_pla_qbz95B_1",
"vme_pla_qcw05",
"VME_QCW05_50Rnd_DCV05",
"VME_QCW05_50Rnd_DAP92",
"ToolKit"] + _generalItems;


_specItems = [_CoItems, _FACItems, _MItems, _SLItems, _FTLItems, _RItems, _RLATItems, _ARItems, _AARItems, _ENGItems, _MKItems, _MGItems, _MATItems, _MTRItems, _SPItems, _HPItems, _VItems, _FYItems];

//////////////////////////////////////////////////////////////////////////////////////////////

[_target, [_this select 0, _restrictionDistance, _specNames, _specSlots, _specTypes, _specItems]] spawn CHSA_fnc_executeLocalArsenal;