_target = sideUnknown;
_restrictionDistance = 15;
_specNames = ["排長","前線火炮觀察員","醫護兵","班長","伍長","步槍兵","步槍兵(反坦克)","自動步槍兵","輔助助手","工程兵","精準射手","排用機槍兵","發射器專精兵","火砲操作人員","狙擊組","直升機組員","機組員","飛行員"];
_specSlots = [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90];
_specTypes = [
	["B_officer_F"],
	["B_soldier_UAV_06_F"],
	["B_medic_F"],
	["B_Soldier_SL_F"],
	["B_Soldier_TL_F"],
	["B_Soldier_F"],
	["B_soldier_LAT_F"],
	["B_soldier_AR_F"],
	["B_soldier_AAR_F","B_soldier_AAT_F","B_Soldier_A_F"],
	[""],
	["B_soldier_M_F"],
	["B_support_MG_F"],
	["B_soldier_AT_F"],
	["B_support_Mort_F","B_support_AMort_F"],
	["B_spotter_F","B_sniper_F"],
	["B_Helipilot_F","B_helicrew_F"],
	["B_crew_F"],
	["B_Pilot_F"]	
];

_generalItems = [
"ACE_microDAGR",
"ACE_MapTools",
"ToolKit",
"ACE_fieldDressing",
"ACE_CableTie",
"ACE_bodyBag",
"ACE_EarPlugs",
"ACE_EntrenchingTool",
"ACE_IR_Strobe_Item",
"ACE_Flashlight_XL50",
"ACE_morphine",
"ACE_rope12",
"ACE_rope15",
"ACE_rope18",
"ACE_rope27",
"ACE_rope36",
"ACE_splint",
"ACE_tourniquet",
"ACE_wirecutter",
"ACRE_PRC148",
"ACRE_PRC152",
"ACRE_PRC343",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemRadio",
"ItemGPS",
"ACE_Chemlight_HiBlue",
"ACE_Chemlight_HiGreen",
"ACE_Chemlight_HiRed",
"ACE_Chemlight_HiWhite",
"ACE_Chemlight_HiYellow",
"ACE_Chemlight_IR",
"Laserbatteries",
"ACE_UAVBattery",
"ACE_SpareBarrel",
"dev_magazine_scannerBattery",
"ACE_M14",
"rhs_mag_an_m14_th3",
"rhs_mag_an_m8hc",
"B_IR_Grenade",
"CUP_HandGrenade_M67",
"rhs_mag_m18_green",
"rhs_mag_m18_purple",
"rhs_mag_m18_red",
"rhs_mag_m18_yellow",
"ACE_M84",
"rhs_mag_mk84",
"rhs_uniform_cu_ocp",
"rhsusf_ach_helmet_headset_ocp",
"rhsusf_ach_helmet_headset_ocp_alt",
"rhsusf_ach_helmet_headset_ess_ocp",
"rhsusf_ach_helmet_headset_ess_ocp_alt",
"rhs_ess_black",
"rhs_googles_clear",
"rhs_googles_black",
"rhsusf_ANPVS_14",
"CUP_hgun_M17_Coyote",
"CUP_21Rnd_9x19_M17_Coyote",
"rhsusf_acc_compm4",
"rhsusf_acc_ACOG",
"rhsusf_acc_ACOG2",
"rhsusf_acc_ACOG3",
"rhsusf_acc_ACOG_RMR",
"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan",
"rhs_mag_30Rnd_556x45_M855A1_Stanag",
"rhsusf_acc_anpeq15_wmx",
"rhsusf_acc_anpeq15side",
"rhsusf_acc_anpeq15_top",
"rhsusf_acc_anpeq15side_bk",
"rhsusf_acc_anpeq15_bk_top",
"rhsusf_acc_kac_grip",
"rhsusf_acc_grip1",
"rhsusf_assault_eagleaiii_ocp",
"rhsusf_falconii_mc",
"rhsusf_spcs_ocp_rifleman_alt",
"rhsusf_spcs_ocp_rifleman",
"B_Kitbag_mcamo",
"B_Carryall_mcamo",
"rhsusf_bino_m24_ARD"
];

_CoItems = [
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"rhs_weap_m4a1_m320",
"rhs_mag_M441_HE",
"rhs_mag_M433_HEDP",
"rhs_mag_M397_HET",
"rhs_mag_m4009",
"rhs_mag_m576",
"rhs_mag_m661_green",
"rhs_mag_m662_red",
"rhs_mag_m713_Red",
"rhs_mag_m714_White",
"rhs_mag_m715_Green",
"rhs_mag_m716_yellow",
"UGL_FlareWhite_F",
"UGL_FlareCIR_F",
"rhsusf_bino_lrf_Vector21",
"ACE_Vector",
"ACE_MX2A",
"rhsusf_spcs_ocp_squadleader",
"rhsusf_spcs_ocp_grenadier"] + _generalItems;
_FACItems = [
"UK3CB_BAF_Soflam_Laserdesignator",
"Laserdesignator",
"CUP_SOFLAM",
"ACE_MX2A",
"B_UAV_01_backpack_F",
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"B_UavTerminal",
"Laserbatteries"] + _generalItems;
_MItems = [
"rhsusf_spcs_ocp_medic",
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"ACE_surgicalKit",
"ACE_adenosine",
"ACE_bloodIV_250",
"ACE_bloodIV",
"ACE_tourniquet",
"ACE_fieldDressing",
"ACE_morphine",
"ACE_epinephrine",
"ACE_bloodIV_500",
"ACE_quikclot",
"ACE_packingBandage",
"ACE_elasticBandage",
"ACE_personalAidKit"] + _generalItems;
_SLItems = [
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"rhs_weap_m4a1_m320",
"rhs_mag_M441_HE",
"rhs_mag_M433_HEDP",
"rhs_mag_M397_HET",
"rhs_mag_m4009",
"rhs_mag_m576",
"rhs_mag_m661_green",
"rhs_mag_m662_red",
"rhs_mag_m713_Red",
"rhs_mag_m714_White",
"rhs_mag_m715_Green",
"rhs_mag_m716_yellow",
"UGL_FlareWhite_F",
"UGL_FlareCIR_F",
"rhsusf_bino_lrf_Vector21",
"ACE_Vector",
"ACE_MX2A",
"rhsusf_spcs_ocp_squadleader",
"rhsusf_spcs_ocp_grenadier"] + _generalItems;
_FTLItems = [
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"rhs_weap_m4a1_m320",
"rhs_mag_M441_HE",
"rhs_mag_M433_HEDP",
"rhs_mag_M397_HET",
"rhs_mag_m4009",
"rhs_mag_m576",
"rhs_mag_m661_green",
"rhs_mag_m662_red",
"rhs_mag_m713_Red",
"rhs_mag_m714_White",
"rhs_mag_m715_Green",
"rhs_mag_m716_yellow",
"UGL_FlareWhite_F",
"UGL_FlareCIR_F",
"rhsusf_bino_lrf_Vector21",
"ACE_Vector",
"ACE_MX2A",
"rhsusf_spcs_ocp_teamleader_alt",
"rhsusf_spcs_ocp_grenadier"] + _generalItems;
_RItems = [
"rhsusf_spcs_ocp_rifleman_alt",
"rhsusf_spcs_ocp_rifleman",
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"B_Carryall_mcamo",
"rhs_mag_maaws_HEAT",
"rhs_mag_maaws_HEDP",
"rhs_mag_maaws_HE",
"rhs_fgm148_magazine_AT",
"rhs_fim92_mag",
"rhsusf_50Rnd_762x51_m80a1epr",
"rhsusf_100Rnd_762x51_m80a1epr",
"rhsusf_200rnd_556x45_mixed_box",
"rhsusf_200Rnd_556x45_box",
"rhsusf_200Rnd_556x45_soft_pouch",
"rhsusf_100Rnd_556x45_soft_pouch"] + _generalItems;
_RLATItems = [
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"rhs_weap_M136",
"rhs_weap_M136_hedp",
"rhs_weap_M136_hp"] + _generalItems;
_ARItems = [
"rhsusf_acc_ELCAN",
"rhsusf_acc_ELCAN_ard",
"rhsusf_spcs_ocp_saw",
"rhs_weap_m249_pip_L_vfg2",
"rhs_weap_m249_pip_S",
"rhsusf_200rnd_556x45_mixed_box",
"rhsusf_200Rnd_556x45_box",
"rhsusf_200Rnd_556x45_soft_pouch",
"rhsusf_100Rnd_556x45_soft_pouch",
"rhsusf_acc_saw_bipod",
"rhsusf_acc_grip4_bipod",
"rhsusf_acc_grip4",
"rhsusf_acc_saw_lw_bipod"] + _generalItems;
_AARItems = [
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"rhsusf_200rnd_556x45_mixed_box",
"rhsusf_200Rnd_556x45_box",
"rhsusf_200Rnd_556x45_soft_pouch",
"rhsusf_100Rnd_556x45_soft_pouch"] + _generalItems;
_ENGItems = [
"ToolKit",
"ACE_Clacker",
"ACE_M26_Clacker",
"ACE_DefusalKit",
"DemoCharge_Remote_Mag",
"SatchelCharge_Remote_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"APERSBoundingMine_Range_Mag",
"SLAMDirectionalMine_Wire_Mag",
"APERSMine_Range_Mag",
"APERSTripMine_Wire_Mag",
"ACE_VMH3",
"rhs_mine_ozm72_a_mag",
"rhs_mine_ozm72_b_mag",
"rhs_mine_ozm72_c_mag",
"rhs_mag_mine_pfm1",
"rhssaf_mine_pma3_mag",
"rhs_mine_msk40p_blue_mag",
"rhs_mine_msk40p_green_mag",
"rhs_mine_msk40p_red_mag",
"rhs_mine_msk40p_white_mag",
"rhs_mine_pmn2_mag",
"rhs_mag_mine_ptm1",
"CUP_PipeBomb_M",
"rhs_mine_sm320_green_mag",
"rhs_mine_sm320_red_mag",
"rhs_mine_sm320_white_mag",
"APERSMine_Range_Mag",
"ACE_VMM3"] + _generalItems;
_MKItems = [
"ACE_RangeCard",
"rhs_weap_sr25",
"rhs_weap_sr25_d",
"rhs_weap_sr25_ec",
"rhs_weap_sr25_ec_d",
"rhsusf_acc_LEUPOLDMK4_2",
"rhsusf_acc_LEUPOLDMK4_2_d",
"rhsusf_acc_LEUPOLDMK4_2_mrds",
"rhsusf_acc_premier_anpvs27",
"rhsusf_20Rnd_762x51_SR25_m118_special_Mag",
"rhsusf_20Rnd_762x51_SR25_mk316_special_Mag",
"rhsusf_acc_harris_bipod",
"rhsusf_spcs_ocp_sniper",
"rhsusf_bino_lrf_Vector21",
"ACE_Vector",
"ACE_MX2A"] + _generalItems;
_MGItems = [
"rhs_weap_m240B",
"rhs_weap_m240G",
"rhsusf_acc_ELCAN",
"rhsusf_acc_ELCAN_ard",
"rhsusf_acc_ACOG_MDO",
"rhsusf_50Rnd_762x51_m80a1epr",
"rhsusf_100Rnd_762x51_m80a1epr"] + _generalItems;
_MATItems = [
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"rhs_weap_maaws",
"rhs_optic_maaws",
"launch_MRAWS_green_F",
"MAA_MAAWS_HEDP502",
"MAA_MAAWS_MT756",
"MAA_MAAWS_ASM509",
"MAA_MAAWS_ADM401",
"MAA_MAAWS_ILLUM545",
"MAA_MAAWS_GMM_HEAT",
"MAA_MAAWS_GMM_HE",
"MAA_MAAWS_GMM_MT",
"MAA_MAAWS_HE441_AB100",
"MAA_MAAWS_HE441_AB250",
"MAA_MAAWS_HE441_AB500",
"rhs_mag_maaws_HEAT",
"rhs_mag_maaws_HEDP",
"rhs_mag_maaws_HE",
"rhs_weap_fgm148",
"rhs_fgm148_magazine_AT",
"rhs_weap_fim92",
"rhs_fim92_mag",
"B_Carryall_mcamo"] + _generalItems;
_MTRItems = [
"ACE_artilleryTable",
"rhsusf_spcs_ocp_rifleman_alt",
"rhsusf_spcs_ocp_rifleman",
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"ace_compat_rhs_usf3_m252_carry"] + _generalItems;
_SPItems = [
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"rhsusf_acc_nt4_black",
"rhs_weap_M107",
"rhs_weap_m24sws",
"rhs_weap_sr25",
"rhs_weap_sr25_d",
"rhs_weap_sr25_ec",
"rhs_weap_sr25_ec_d",
"rhs_weap_XM2010_wd",
"rhs_weap_XM2010_d",
"rhsusf_acc_M2010S_d",
"rhsusf_acc_M8541_d",
"rhsusf_acc_LEUPOLDMK4_2",
"rhsusf_acc_LEUPOLDMK4_2_d",
"rhsusf_acc_LEUPOLDMK4_2_mrds",
"rhsusf_acc_nxs_5522x56_md_sun",
"rhsusf_acc_premier_anpvs27",
"rhsusf_20Rnd_762x51_SR25_m118_special_Mag",
"rhsusf_20Rnd_762x51_SR25_mk316_special_Mag",
"rhsusf_spcs_ocp_sniper",
"rhsusf_acc_harris_bipod",
"rhsusf_acc_M8541_mrds",
"rhsusf_acc_premier_mrds",
"rhsusf_5Rnd_762x51_m118_special_Mag",
"rhsusf_5Rnd_762x51_m993_Mag",
"rhsusf_5Rnd_300winmag_xm2010",
"rhsusf_mag_10Rnd_STD_50BMG_M33",
"rhsusf_mag_10Rnd_STD_50BMG_mk211",
"rhsusf_acc_m24_muzzlehider_black",
"rhsusf_acc_m24_silencer_black",
"rhsusf_acc_aac_762sdn6_silencer",
"rhsusf_acc_M2010S_wd",
"rhsusf_acc_SR25S",
"rhsusf_acc_SR25S_d",
"U_B_FullGhillie_sard",
"U_B_FullGhillie_lsh",
"rhsusf_acc_harris_swivel",
"rhsusf_spcs_ocp_sniper",
"ACE_RangeCard",
"ACE_SpottingScope",
"ACE_Tripod",
"ACE_Flashlight_KSF1",
"ACE_Kestrel4500"] + _generalItems;
_HPItems = [
"ToolKit",
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"rhsusf_spcs_ocp",
"rhsusf_weap_MP7A2",
"CUP_smg_MP5A5_Rail",
"CUP_30Rnd_9x19_MP5",
"rhsusf_mag_40Rnd_46x30_FMJ",
"rhsusf_hgu56p_visor_black",
"rhsusf_hgu56p_visor_mask_black_skull",
"rhsusf_hgu56p_visor_green",
"rhsusf_hgu56p_visor_mask_green_mo",
"rhsusf_hgu56p_visor",
"rhsusf_hgu56p_visor_mask_skull",
"rhsusf_hgu56p_visor_pink",
"rhsusf_hgu56p_visor_mask_pink",
"rhsusf_hgu56p_visor_saf",
"rhsusf_hgu56p_visor_mask_saf",
"rhsusf_hgu56p_visor_mask_smiley",
"rhsusf_hgu56p_visor_tan",
"rhsusf_hgu56p_visor_mask_tan",
"rhsusf_hgu56p_visor_usa",
"rhsusf_hgu56p_visor_white",
"rhsusf_ihadss"] + _generalItems;
_VItems = [
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_mstock",
"rhs_weap_m4a1",
"rhs_weap_m4a1_mstock",
"rhsusf_spcs_ocp_crewman",
"rhsusf_cvc_green_helmet",
"rhsusf_cvc_helmet",
"ToolKit"] + _generalItems;
_FYItems = [
"JS_JC_FA18_PilotHelmet",
"U_B_PilotCoveralls",
"H_PilotHelmetFighter_B",
"SMG_01_F",
"30Rnd_45ACP_Mag_SMG_01",
"SMG_03C_TR_khaki",
"50Rnd_570x28_SMG_03"] + _generalItems;


_specItems = [_CoItems, _FACItems, _MItems, _SLItems, _FTLItems, _RItems, _RLATItems, _ARItems, _AARItems, _ENGItems, _MKItems, _MGItems, _MATItems, _MTRItems, _SPItems, _HPItems, _VItems, _FYItems];

//////////////////////////////////////////////////////////////////////////////////////////////

[_target, [_this select 0, _restrictionDistance, _specNames, _specSlots, _specTypes, _specItems]] spawn CHSA_fnc_executeLocalArsenal;