_target = sideUnknown;
_restrictionDistance = 15;
_specNames = ["排長","前線火炮觀察員","醫護兵","班長","伍長","步槍兵","步槍兵(反坦克)","自動步槍兵","輔助助手","工程兵","精準射手","排用機槍兵","發射器專精兵","火砲操作人員","狙擊組","直升機組員","機組員","飛行員"];
_specSlots = [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90];
_specTypes = [
	["B_officer_F"],
	["B_soldier_UAV_06_F"],
	["B_medic_F"],
	["B_Soldier_SL_F"],
	["B_Soldier_TL_F"],
	["B_Soldier_F"],
	["B_soldier_LAT_F"],
	["B_soldier_AR_F"],
	["B_soldier_AAR_F","B_soldier_AAT_F","B_Soldier_A_F"],
	[""],
	["B_soldier_M_F"],
	["B_support_MG_F"],
	["B_soldier_AT_F"],
	["B_support_Mort_F","B_support_AMort_F"],
	["B_spotter_F","B_sniper_F"],
	["B_Helipilot_F","B_helicrew_F"],
	["B_crew_F"],
	["B_Pilot_F"]	
];

_generalItems = [
"ACE_microDAGR",
"ACE_SpraypaintBlack",
"ACE_SpraypaintBlue",
"ACE_SpraypaintGreen",
"ACE_SpraypaintRed",
"ACE_MapTools",
"ACE_SpareBarrel",
"ToolKit",
"ACE_fieldDressing",
"ACE_CableTie",
"ACE_bodyBag",
"ACE_EarPlugs",
"ACE_EntrenchingTool",
"ACE_IR_Strobe_Item",
"ACE_Flashlight_XL50",
"ACE_morphine",
"ACE_rope12",
"ACE_rope15",
"ACE_rope18",
"ACE_rope27",
"ACE_rope36",
"ACE_splint",
"ACE_tourniquet",
"ACE_wirecutter",
"ACRE_PRC148",
"ACRE_PRC152",
"ACRE_PRC343",
"ACRE_PRC77",
"ACRE_PRC117F",
"gac_JSDF_W_R_Type89_H",
"gac_JSDF_W_R_Type89F_H",
"gac_JGSDF_P220",
"gac_jsdf_sfp9",
"gac_JSDF_15Rnd_9x19_Mag",
"gac_JGSDF_BDU",
"gac_JGSDF_Vest_type3_sh_new",
"gac_JGSDF_Vest_type3_sh",
"gac_JGSDF_Backpack1",
"gac_JGSDF_Backpack2",
"gac_JGSDF_Bag",
"rhsusf_ANPVS_14",
"VSM_flightglove_standalone_NVG",
"VSM_511_flightglove_Black_standalone",
"VSM_magpul_flightglove_cut_standalone_NVG",
"B_Carryall_oli",
"B_AssaultPack_khk",
"gac_JGSDF_helmet",
"gac_JGSDF_helmet_goggle",
"VSM_511_flightglove_Black_standalone",
"VSM_511_flightglove_OD_standalone",
"gac_JSDF_W_R_Type89_bipod",
"gac_JSDF_W_R_Type89_laser_JVS_V1",
"gac_optic_JGSDF_Dotsight",
"30Rnd_556x45_Stanag",
"gac_JSDF_9Rnd_9x19_Mag",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemRadio",
"ItemGPS",
"ACE_Chemlight_HiBlue",
"ACE_Chemlight_HiGreen",
"ACE_Chemlight_HiRed",
"ACE_Chemlight_HiWhite",
"ACE_Chemlight_HiYellow",
"ACE_Chemlight_IR",
"ACE_Chemlight_UltraHiOrange",
"ACE_Chemlight_Orange",
"rhs_grenade_m15_mag",
"rhs_grenade_mkiiia1_mag",
"rhs_mag_mk3a2",
"rhs_mag_an_m14_th3",
"HandGrenade",
"rhs_mag_m18_green",
"rhs_mag_m18_purple",
"rhs_mag_m18_red",
"rhs_mag_m18_yellow",
"ACE_M84",
"rhs_mag_mk84",
"B_IR_Grenade",
"rhs_ess_black",
"rhs_googles_clear",
"rhs_googles_black",
"rhsusf_bino_m24_ARD",
"ACE_UAVBattery"
];

_CoItems = [
"gac_JSDF_M_RG_22_APAV",
"rhs_weap_M320",
"rhs_mag_M441_HE",
"rhs_mag_M433_HEDP",
"rhs_mag_M397_HET",
"rhs_mag_m4009",
"rhs_mag_m576",
"rhs_mag_m661_green",
"rhs_mag_m662_red",
"rhs_mag_m713_Red",
"rhs_mag_m714_White",
"rhs_mag_m715_Green",
"rhs_mag_m716_yellow",
"UGL_FlareWhite_F",
"UGL_FlareCIR_F",
"rhsusf_bino_lrf_Vector21",
"ACE_Vector",
"ACE_MX2A"] + _generalItems;
_FACItems = [
"Laserdesignator",
"ACE_MX2A",
"B_UAV_01_backpack_F",
"B_UavTerminal",
"Laserbatteries"] + _generalItems;
_MItems = [
"ACE_surgicalKit",
"ACE_adenosine",
"ACE_bloodIV_250",
"ACE_bloodIV",
"ACE_tourniquet",
"ACE_fieldDressing",
"ACE_morphine",
"ACE_epinephrine",
"ACE_bloodIV_500",
"ACE_quikclot",
"ACE_packingBandage",
"ACE_elasticBandage",
"ACE_personalAidKit"] + _generalItems;
_SLItems = [
"gac_JSDF_M_RG_22_APAV",
"rhs_weap_M320",
"rhs_mag_M441_HE",
"rhs_mag_M433_HEDP",
"rhs_mag_M397_HET",
"rhs_mag_m4009",
"rhs_mag_m576",
"rhs_mag_m661_green",
"rhs_mag_m662_red",
"rhs_mag_m713_Red",
"rhs_mag_m714_White",
"rhs_mag_m715_Green",
"rhs_mag_m716_yellow",
"UGL_FlareWhite_F",
"UGL_FlareCIR_F",
"rhsusf_bino_lrf_Vector21",
"ACE_Vector",
"ACE_MX2A"] + _generalItems;
_FTLItems = [
"gac_JSDF_M_RG_22_APAV",
"rhs_weap_M320",
"rhs_mag_M441_HE",
"rhs_mag_M433_HEDP",
"rhs_mag_M397_HET",
"rhs_mag_m4009",
"rhs_mag_m576",
"rhs_mag_m661_green",
"rhs_mag_m662_red",
"rhs_mag_m713_Red",
"rhs_mag_m714_White",
"rhs_mag_m715_Green",
"rhs_mag_m716_yellow",
"UGL_FlareWhite_F",
"UGL_FlareCIR_F",
"rhsusf_bino_lrf_Vector21",
"ACE_Vector",
"ACE_MX2A"] + _generalItems;
_RItems = [
"200Rnd_556x45_Box_Tracer_Red_F",
"gac_JSDF_M_MG_Minimi_200R",
"gac_LMAT_Mag",
"Titan_AA",
"gac_110mmLAM_JM12"] + _generalItems;
_RLATItems = [
"gac_JSDF_W_RR_110mm",
"gac_110mmLAM_JM12",
"rhs_weap_M136",
"rhs_weap_M136_hedp",
"rhs_weap_M136_hp"] + _generalItems;
_ARItems = [
"gac_JSDF_W_MG_MINIMI",
"200Rnd_556x45_Box_Tracer_Red_F",
"gac_JSDF_M_MG_Minimi_200R",
"rhsusf_200rnd_556x45_mixed_box",
"rhsusf_200Rnd_556x45_box",
"rhsusf_200Rnd_556x45_soft_pouch",
"rhsusf_100Rnd_556x45_soft_pouch"] + _generalItems;
_AARItems = [
"200Rnd_556x45_Box_Tracer_Red_F",
"gac_JSDF_M_MG_Minimi_200R",
"rhsusf_200rnd_556x45_mixed_box",
"rhsusf_200Rnd_556x45_box",
"rhsusf_200Rnd_556x45_soft_pouch",
"rhsusf_100Rnd_556x45_soft_pouch"] + _generalItems;
_ENGItems = [
"ToolKit",
"ACE_Clacker",
"ACE_M26_Clacker",
"ACE_DefusalKit",
"DemoCharge_Remote_Mag",
"SatchelCharge_Remote_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"APERSBoundingMine_Range_Mag",
"SLAMDirectionalMine_Wire_Mag",
"APERSMine_Range_Mag",
"APERSTripMine_Wire_Mag",
"ACE_VMH3",
"rhs_mine_ozm72_a_mag",
"rhs_mine_ozm72_b_mag",
"rhs_mine_ozm72_c_mag",
"rhs_mag_mine_pfm1",
"rhssaf_mine_pma3_mag",
"rhs_mine_msk40p_blue_mag",
"rhs_mine_msk40p_green_mag",
"rhs_mine_msk40p_red_mag",
"rhs_mine_msk40p_white_mag",
"rhs_mine_pmn2_mag",
"rhs_mag_mine_ptm1",
"rhs_mine_sm320_green_mag",
"rhs_mine_sm320_red_mag",
"rhs_mine_sm320_white_mag",
"APERSMine_Range_Mag",
"ACE_VMM3"] + _generalItems;
_MKItems = [
"ACE_Vector",
"ACE_RangeCard",
"gac_JSDF_W_R_Type64",
"gac_JSDF_W_Scope_JM84_t64R",
"gac_JSDF_M_R_Type64",
"rhsusf_bino_lrf_Vector21",
"ACE_Vector",
"ACE_MX2A"] + _generalItems;
_MGItems = [
"rhs_weap_m240B",
"rhs_weap_m240G",
"rhsusf_acc_ELCAN",
"rhsusf_acc_ELCAN_ard",
"rhsusf_acc_ACOG_MDO",
"rhsusf_50Rnd_762x51_m80a1epr",
"rhsusf_100Rnd_762x51_m80a1epr"] + _generalItems;
_MATItems = [
"launch_MRAWS_green_F",
"rhs_weap_maaws",
"rhs_optic_maaws",
"MAA_MAAWS_HEDP502",
"MAA_MAAWS_MT756",
"MAA_MAAWS_ASM509",
"MAA_MAAWS_ADM401",
"MAA_MAAWS_ILLUM545",
"MAA_MAAWS_GMM_HEAT",
"MAA_MAAWS_GMM_HE",
"MAA_MAAWS_GMM_MT",
"MAA_MAAWS_HE441_AB100",
"MAA_MAAWS_HE441_AB250",
"MAA_MAAWS_HE441_AB500",
"rhs_mag_maaws_HEAT",
"rhs_mag_maaws_HEDP",
"rhs_mag_maaws_HE",
"gac_JSDF_W_LMAT",
"gac_optic_LMAT_nv",
"gac_LMAT_Mag",
"Titan_AA",
"rhs_weap_fgm148",
"rhs_fgm148_magazine_AT",
"rhs_weap_fim92",
"rhs_fim92_mag"] + _generalItems;
_MTRItems = [
"ACE_artilleryTable"] + _generalItems;
_SPItems = [
"rhs_weap_m24sws",
"rhs_weap_M107_w",
"rhsusf_mag_10Rnd_STD_50BMG_mk211",
"rhsusf_mag_10Rnd_STD_50BMG_M33",
"ACE_10Rnd_127x99_Mag",
"ACE_10Rnd_127x99_API_Mag",
"ACE_10Rnd_127x99_AMAX_Mag",
"rhsusf_acc_m24_silencer_black",
"rhsusf_5Rnd_762x51_m118_special_Mag",
"rhsusf_acc_harris_swivel",
"V_Chestrig_rgr",
"V_Chestrig_khk",
"H_Booniehat_oli",
"H_Booniehat_khk_hs",
"ACE_Vector",
"RKSL_optic_PMII_312_sunshade",
"RKSL_optic_PMII_312",
"ACE_7Rnd_408_305gr_Mag",
"rhsusf_acc_M8541_d",
"RKSL_optic_PMII_525",
"rhsusf_acc_LEUPOLDMK4_2",
"rhsusf_acc_LEUPOLDMK4_2_d",
"rhsusf_acc_LEUPOLDMK4_2_mrds",
"rhsusf_acc_nxs_5522x56_md_sun",
"rhsusf_acc_premier_anpvs27",
"rhsusf_20Rnd_762x51_SR25_m118_special_Mag",
"rhsusf_20Rnd_762x51_SR25_mk316_special_Mag",
"rhsusf_spcs_ocp_sniper",
"rhsusf_acc_harris_bipod",
"rhsusf_acc_M8541_mrds",
"rhsusf_acc_premier_mrds",
"rhsusf_5Rnd_762x51_m118_special_Mag",
"rhsusf_5Rnd_762x51_m993_Mag",
"rhsusf_5Rnd_300winmag_xm2010",
"rhsusf_mag_10Rnd_STD_50BMG_M33",
"rhsusf_mag_10Rnd_STD_50BMG_mk211",
"rhsusf_acc_aac_762sdn6_silencer",
"U_B_FullGhillie_sard",
"U_B_FullGhillie_lsh",
"rhsusf_acc_harris_swivel",
"rhsusf_spcs_ocp_sniper",
"ACE_RangeCard",
"ACE_SpottingScope",
"ACE_Tripod",
"ACE_Flashlight_KSF1",
"ACE_Kestrel4500"] + _generalItems;
_HPItems = [
"ToolKit",
"gac_JGSDF_pilot_helmet",
"rhsusf_ihadss"] + _generalItems;
_VItems = [
"gac_JGSDF_tank_helmet_old",
"ToolKit"] + _generalItems;
_FYItems = [
"gac_JASDF_pilot_helmet",
"JS_JC_FA18_PilotHelmet",
"U_B_PilotCoveralls",
"H_PilotHelmetFighter_B",
"SMG_01_F",
"30Rnd_45ACP_Mag_SMG_01",
"SMG_03C_TR_khaki",
"50Rnd_570x28_SMG_03"] + _generalItems;


_specItems = [_CoItems, _FACItems, _MItems, _SLItems, _FTLItems, _RItems, _RLATItems, _ARItems, _AARItems, _ENGItems, _MKItems, _MGItems, _MATItems, _MTRItems, _SPItems, _HPItems, _VItems, _FYItems];

//////////////////////////////////////////////////////////////////////////////////////////////

[_target, [_this select 0, _restrictionDistance, _specNames, _specSlots, _specTypes, _specItems]] spawn CHSA_fnc_executeLocalArsenal;