_target = sideUnknown;
_restrictionDistance = 15;
_specNames = ["排長","前線火炮觀察員","醫護兵","班長","伍長","步槍兵","步槍兵(反坦克)","自動步槍兵","輔助助手","工程兵","精準射手","排用機槍兵","發射器專精兵","火砲操作人員","狙擊組","直升機組員","機組員","飛行員"];
_specSlots = [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90];
_specTypes = [
	["O_officer_F"],
	["O_soldier_UAV_06_F"],
	["O_medic_F"],
	["O_Soldier_SL_F"],
	["O_Soldier_TL_F"],
	["O_Soldier_F"],
	["O_soldier_LAT_F"],
	["O_soldier_AR_F"],
	["O_soldier_AAR_F","O_soldier_AAT_F","O_Soldier_A_F"],
	[""],
	["O_soldier_M_F"],
	["O_support_MG_F"],
	["O_soldier_AT_F"],
	["O_support_Mort_F","O_support_AMort_F"],
	["O_spotter_F","O_sniper_F"],
	["O_Helipilot_F","O_helicrew_F"],
	["O_crew_F"],
	["O_Pilot_F"]	
];

_generalItems = [
"rhs_uniform_vkpo_gloves_alt",
"rhs_6b45_rifleman",
"rhs_6b45_rifleman_2",
"rhs_rk_sht_30_emr",
"rhs_tortila_emr",
"rhs_6b47_emr_2",
"rhs_6b47_emr_1",
"rhs_6b47_emr",
"rhs_facewear_6m2_1",
"rhs_weap_ak74m",
"rhs_acc_dtk",
"rhs_acc_2dpZenit",
"rhs_acc_perst1ik",
"rhs_acc_pkas",
"rhs_acc_1p78",
"rhs_acc_okp7_dovetail",
"rhs_30Rnd_545x39_7N22_AK",
"16Rnd_9x21_Mag",
"ACE_CableTie",
"ACE_UAVBattery",
"ACE_SpraypaintBlack",
"ACE_SpraypaintBlue",
"ACE_SpraypaintGreen",
"ACE_SpraypaintRed",
"rhs_1PN138",
"hgun_Rook40_F",
"G_Tactical_Clear",
"G_Tactical_Black",
"rhs_googles_black",
"rhs_googles_clear",
"Binocular",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemRadioAcreFlagged",
"ItemGPS",
"ACE_wirecutter",
"ACE_splint",
"ACE_MapTools",
"ACE_fieldDressing",
"ACE_SpraypaintRed",
"ACE_SpraypaintGreen",
"ACE_EarPlugs",
"ACE_tourniquet",
"ACRE_PRC343",
"ACE_Flashlight_XL50",
"ACE_EntrenchingTool",
"ACE_morphine",
"ACE_Flashlight_MX991",
"ACE_rope12",
"ACE_rope15",
"ACE_rope18",
"ACE_rope36",
"ACE_rope27",
"ACE_SpareBarrel",
"O_IR_Grenade",
"ACE_Chemlight_UltraHiOrange",
"ACE_Chemlight_HiGreen",
"ACE_Chemlight_HiBlue",
"ACE_Chemlight_Orange",
"ACE_Chemlight_White",
"ACE_Chemlight_IR",
"ACE_Chemlight_HiWhite",
"ACE_Chemlight_HiRed",
"ACE_Chemlight_HiYellow",
"Chemlight_red",
"Chemlight_green",
"Chemlight_blue",
"Chemlight_yellow",
"LIB_F1",
"rhs_mag_f1",
"rhs_mag_nspd",
"rhs_mag_nspn_green",
"rhs_mag_nspn_red",
"rhs_mag_nspn_yellow",
"LIB_RDG",
"rhs_mag_rdg2_black",
"rhs_mag_rdg2_white",
"LIB_Rg42",
"rhs_mag_rgd5",
"CUP_HandGrenade_RGD5",
"Grenade_min_rf_rgd_5",
"rhs_mag_rgn",
"rhs_mag_rgo",
"CUP_HandGrenade_RGO",
"rhs_mag_zarya2",
"MiniGrenade",
"ACE_EntrenchingTool",
"ACRE_VHF30108SPIKE",
"ACRE_VHF30108",
"ACRE_VHF30108MAST",
"ACE_IR_Strobe_Item",
"ACE_bodyBag",
"ToolKit",
"ACE_RangeCard",
"ACE_CableTie",
"ACE_MapTools",
"ACRE_PRC152",
"ACRE_PRC148",
"ACRE_PRC77",
"ACRE_PRC117F"];

_CoItems = [
"rhs_6b45_grn",
"rhs_6b45_off",
"rhs_pdu4",
"CUP_Vest_RUS_6B45_Sh117_VOG",
"rhs_weap_ak74m_gp25",
"ACE_MX2A",
"hgun_Rook40_F",
"rhs_VOG25",
"rhs_VOG25P",
"rhs_VG40TB",
"rhs_VG40SZ",
"rhs_VG40OP_white",
"rhs_VG40OP_green",
"rhs_VG40OP_red",
"rhs_GRD40_White",
"rhs_GRD40_Green",
"rhs_GRD40_Red",
"rhs_GDM40",
"rhs_VG40MD",
"16Rnd_9x21_Mag"] + _generalItems;
_FACItems = [
"rhs_pdu4",
"ACE_MX2A",
"Laserdesignator",
"O_UAV_01_backpack_F",
"O_UavTerminal",
"Laserbatteries",
"hgun_Rook40_F",
"16Rnd_9x21_Mag"] + _generalItems;
_MItems = [
"ACE_surgicalKit",
"ACE_adenosine",
"ACE_bloodIV_250",
"ACE_bloodIV",
"ACE_tourniquet",
"ACE_fieldDressing",
"ACE_morphine",
"ACE_epinephrine",
"ACE_bloodIV_500",
"ACE_quikclot",
"ACE_packingBandage",
"ACE_elasticBandage",
"ACE_personalAidKit"] + _generalItems;
_SLItems = [
"rhs_6b45_grn",
"rhs_pdu4",
"ACE_MX2A"] + _generalItems;
_FTLItems = [
"rhs_6b45_grn",
"rhs_pdu4",
"rhs_weap_ak74m_gp25",
"rhs_VOG25",
"rhs_VOG25P",
"rhs_VG40TB",
"rhs_VG40SZ",
"rhs_VG40OP_white",
"rhs_VG40OP_green",
"rhs_VG40OP_red",
"rhs_GRD40_White",
"rhs_GRD40_Green",
"rhs_GRD40_Red",
"rhs_GDM40",
"rhs_VG40MD",
"ACE_MX2A"] + _generalItems;
_RItems = [
"rhs_weap_ak74m",
"rhs_rpg7_PG7VL_mag",
"rhs_rpg7_PG7V_mag",
"rhs_rpg7_PG7VM_mag",
"rhs_rpg7_PG7VS_mag",
"rhs_rpg7_PG7VR_mag",
"rhs_rpg7_OG7V_mag",
"rhs_rpg7_TBG7V_mag",
"rhs_rpg7_type69_airburst_mag",
"RPG7_F",
"rhs_rpg_empty",
"rhs_100Rnd_762x54mmR",
"rhs_100Rnd_762x54mmR_green",
"rhs_100Rnd_762x54mmR_7N13",
"rhs_100Rnd_762x54mmR_7N26",
"rhs_100Rnd_762x54mmR_7BZ3",
"150Rnd_762x54_Box",
"150Rnd_762x54_Box_Tracer"] + _generalItems;
_RLATItems = [
"rhs_rpg_empty",
"rhs_weap_rpg26",
"rhs_weap_rpg7",
"rhs_acc_pgo7v3",
"rhs_rpg7_PG7VL_mag",
"rhs_rpg7_PG7V_mag",
"rhs_rpg7_PG7VM_mag",
"rhs_rpg7_PG7VS_mag",
"rhs_rpg7_PG7VR_mag",
"rhs_rpg7_OG7V_mag",
"rhs_rpg7_TBG7V_mag",
"CUP_PG7VR_M",
"CUP_OG7_M",
"CUP_TBG7V_M",
"rhs_rpg7_type69_airburst_mag",
"RPG7_F",
"CUP_PG7V_M",
"CUP_PG7VM_M",
"CUP_PG7VL_M",
"rhs_weap_rshg2"] + _generalItems;
_ARItems = [
"rhs_6b45_mg",
"rhs_weap_pkm",
"rhs_weap_pkp",
"rhs_100Rnd_762x54mmR",
"rhs_100Rnd_762x54mmR_green",
"rhs_100Rnd_762x54mmR_7N13",
"rhs_100Rnd_762x54mmR_7N26",
"rhs_100Rnd_762x54mmR_7BZ3",
"150Rnd_762x54_Box",
"150Rnd_762x54_Box_Tracer"] + _generalItems;
_AARItems = [
"rhs_100Rnd_762x54mmR",
"rhs_100Rnd_762x54mmR_green",
"rhs_100Rnd_762x54mmR_7N13",
"rhs_100Rnd_762x54mmR_7N26",
"rhs_100Rnd_762x54mmR_7BZ3",
"150Rnd_762x54_Box",
"150Rnd_762x54_Box_Tracer"] + _generalItems;
_ENGItems = [
"rhs_rk_sht_30_emr_engineer_empty",
"ACE_Clacker",
"ACE_M26_Clacker",
"ACE_DefusalKit",
"DemoCharge_Remote_Mag",
"SatchelCharge_Remote_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"APERSBoundingMine_Range_Mag",
"SLAMDirectionalMine_Wire_Mag",
"APERSMine_Range_Mag",
"APERSTripMine_Wire_Mag",
"ACE_VMH3",
"rhs_mine_ozm72_a_mag",
"rhs_mine_ozm72_b_mag",
"rhs_mine_ozm72_c_mag",
"rhs_mag_mine_pfm1",
"rhssaf_mine_pma3_mag",
"rhs_mine_msk40p_blue_mag",
"rhs_mine_msk40p_green_mag",
"rhs_mine_msk40p_red_mag",
"rhs_mine_msk40p_white_mag",
"rhs_mine_pmn2_mag",
"rhs_mag_mine_ptm1",
"rhs_mine_sm320_green_mag",
"rhs_mine_sm320_red_mag",
"rhs_mine_sm320_white_mag",
"APERSMine_Range_Mag",
"ACE_VMM3"] + _generalItems;
_MKItems = [
"ACE_RangeCard",
"rhs_pdu4",
"rhs_weap_svdp",
"rhs_weap_svdp_wd",
"rhs_weap_svdp_npz",
"rhs_weap_svdp_wd_npz",
"ACE_optic_LRPS_2D",
"AGE_optic_DMS",
"rhs_acc_1pn93_1",
"rhs_acc_1pn34",
"rhs_acc_pso1m21",
"rhs_10Rnd_762x54mmR_7N1",
"rhs_10Rnd_762x54mmR_7N14",
"rhs_acc_dh520x56",
"rhs_acc_harris_swivel",
"rhs_weap_pp2000_folded",
"rhs_mag_9x19mm_7n21_44",
"rhs_mag_9x19mm_7n31_44"] + _generalItems;
_MGItems = [
"RHS_DShkM_Gun_Bag",
"RHS_DShkM_TripodHigh_Bag",
"RHS_DShkM_TripodLow_Bag",
"RHS_Kord_Tripod_Bag",
"RHS_Kord_Gun_Bag",
"RHS_NSV_Tripod_Bag",
"RHS_NSV_Gun_Bag",
"RHS_AGS30_Tripod_Bag",
"ace_compat_rhs_afrf3_mag_VOG30_30",
"ace_compat_rhs_afrf3_mag_VOG17m_30",
"ace_compat_rhs_afrf3_mag_GPD30_30",
"ace_csw_50Rnd_127x108_mag",
"RHS_AGS30_Gun_Bag"] + _generalItems;
_MATItems = [
"RHS_Metis_Gun_Bag",
"RHS_Metis_Tripod_Bag",
"RHS_Kornet_Gun_Bag",
"RHS_Kornet_Tripod_Bag",
"RHS_SPG9_Gun_Bag",
"RHS_SPG9_Tripod_Bag",
"rhs_weap_igla",
"launch_O_Vorona_green_F",
"rhs_mag_9k38_rocket",
"Vorona_HEAT",
"Vorona_HE",
"ace_compat_rhs_afrf3_mag_9M131M",
"ace_compat_rhs_afrf3_mag_9M131F",
"ace_compat_rhs_afrf3_mag_9m133",
"ace_compat_rhs_afrf3_mag_PG9V",
"ace_compat_rhs_afrf3_mag_OG9V",
"B_Carryall_khk"] + _generalItems;
_MTRItems = [
"RHS_Podnos_Bipod_Bag",
"ACE_1Rnd_82mm_Mo_HE",
"ACE_1Rnd_82mm_Mo_Illum",
"ACE_1Rnd_82mm_Mo_Smoke",
"RHS_Podnos_Gun_Bag"] + _generalItems;
_SPItems = [
"ACE_Kestrel4500",
"ACE_RangeCard",
"rhs_pdu4",
"rhs_weap_t5000",
"hlc_optic_goshawk",
"Laserdesignator",
"srifle_GM6_F",
"rhs_acc_tgpv2",
"ACE_MX2A",
"ACE_Tripod",
"hlc_optic_goshawk",
"rhs_acc_dh520x56",
"rhs_5Rnd_338lapua_t5000",
"rhs_acc_harris_swivel",
"rhs_weap_svdp_wd",
"rhs_weap_svdp_wd_npz",
"rhs_weap_svdp_npz",
"rhs_weap_svds_npz",
"rhs_acc_pso1m21",
"rhs_10Rnd_762x54mmR_7N1",
"rhs_10Rnd_762x54mmR_7N14",
"srifle_DMR_01_F",
"rhs_acc_dh520x56",
"rhs_acc_harris_swivel",
"rhsusf_acc_premier_mrds",
"rhsusf_acc_LEUPOLDMK4_2_mrds",
"rhs_weap_pp2000_folded",
"rhs_mag_9x19mm_7n21_44",
"rhs_mag_9x19mm_7n31_44"] + _generalItems;
_HPItems = [
"rhs_weap_aks74u",
"rhs_weap_pp2000",
"rhs_acc_ekp8_18",
"rhs_mag_9x19mm_7n21_20",
"rhs_uniform_df15_tan",
"rhs_mag_9x19mm_7n31_44",
"rhs_mag_9x19mm_7n21_44",
"rhs_zsh7a_mike_green_alt",
"rhs_zsh7a_mike_green"] + _generalItems;
_VItems = [
"rhs_6b48",
"rhs_weap_aks74u",
"rhs_mag_9x19mm_7n21_20",
"rhs_mag_9x19mm_7n31_44",
"rhs_mag_9x19mm_7n21_44",
"rhs_tsh4",
"rhs_tsh4_bala",
"rhs_tsh4_ess",
"rhs_tsh4_ess_bala",
"ToolKit"] + _generalItems;
_FYItems = [
"rhs_weap_aks74u",
"rhs_weap_pp2000",
"rhs_acc_ekp8_18",
"rhs_uniform_df15_tan",
"rhs_mag_9x19mm_7n31_44",
"rhs_mag_9x19mm_7n21_44",
"H_PilotHelmetFighter_O",
"U_O_PilotCoveralls",
"rhs_zsh7a_alt",
"rhs_uniform_df15"] + _generalItems;


_specItems = [_CoItems, _FACItems, _MItems, _SLItems, _FTLItems, _RItems, _RLATItems, _ARItems, _AARItems, _ENGItems, _MKItems, _MGItems, _MATItems, _MTRItems, _SPItems, _HPItems, _VItems, _FYItems];

//////////////////////////////////////////////////////////////////////////////////////////////

[_target, [_this select 0, _restrictionDistance, _specNames, _specSlots, _specTypes, _specItems]] spawn CHSA_fnc_executeLocalArsenal;