_target = sideUnknown;
_restrictionDistance = 15;
_specNames = ["排長","前線火炮觀察員","醫護兵","班長","伍長","步槍兵","步槍兵(反坦克)","自動步槍兵","輔助助手","工程兵","精準射手","排用機槍兵","發射器專精兵","火砲操作人員","狙擊組","直升機組員","機組員","飛行員"];
_specSlots = [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90];
_specTypes = [
	["I_officer_F"],
	["I_soldier_UAV_06_F"],
	["I_medic_F"],
	["I_Soldier_SL_F"],
	["I_Soldier_TL_F"],
	["I_Soldier_F"],
	["I_soldier_LAT_F"],
	["I_soldier_AR_F"],
	["I_soldier_AAR_F","I_soldier_AAT_F","I_Soldier_A_F"],
	[""],
	["I_soldier_M_F"],
	["I_support_MG_F"],
	["I_soldier_AT_F"],
	["I_support_Mort_F","I_support_AMort_F"],
	["I_spotter_F","I_sniper_F"],
	["I_Helipilot_F","I_helicrew_F"],
	["I_crew_F"],
	["I_Pilot_F"]	
];

_generalItems = [
"ACE_SpareBarrel",
"ACE_CableTie",
"ACE_UAVBattery",
"UK3CB_G3A3",
"UK3CB_G3A3V",
"CUP_arifle_G3A3_ris",
"CUP_arifle_G3A3_modern_ris",
"CUP_hgun_Browning_HP",
"CUP_13Rnd_9x19_Browning_HP",
"20Rnd_762x51_Mag",
"CUP_20Rnd_762x51_G3",
"UK3CB_AAF_B_U_CombatUniform_DIGI_GRN",
"UK3CB_AAF_B_U_CombatUniform_Shortsleeve_DIGI_GRN",
"UK3CB_V_Falcon_2",
"UK3CB_V_Falcon_7",
"UK3CB_V_Falcon_8",
"UK3CB_AAF_O_V_Eagle_RIF_DIGI_GRN",
"UK3CB_AAF_B_B_CARRYALL_DIGI_GRN",
"UK3CB_AAF_B_B_FIELDPACK_DIGI_GRN",
"UK3CB_AAF_B_H_PASGT_DIGI_GRN",
"UK3CB_AAF_B_H_PASGT_RHINO_DIGI_GRN",
"UK3CB_AAF_O_H_6b27m_DIGI_GRN",
"UK3CB_AAF_I_H_MKVI_Helmet_A_GRN",
"rhs_googles_clear",
"rhs_googles_black",
"rhs_ess_black",
"UK3CB_ANPVS7",
"ItemMap",
"ItemCompass",
"ItemWatch",
"ItemRadio",
"ItemGPS",
"rhssaf_zrak_rd7j",
"ACE_splint",
"ACE_fieldDressing",
"ACE_bodyBag",
"ToolKit",
"ACE_RangeCard",
"ACE_DefusalKit",
"ACE_artilleryTable",
"ACE_rope12",
"ACE_rope15",
"ACE_rope18",
"ACE_rope27",
"ACE_rope36",
"ACE_EarPlugs",
"ACE_tourniquet",
"ACRE_PRC148",
"ACRE_PRC152",
"ACRE_PRC343",
"ACE_EntrenchingTool",
"ACE_Flashlight_MX991",
"ACE_Flashlight_XL50",
"ACE_morphine",
"ACE_wirecutter",
"ACE_MapTools",
"I_IR_Grenade",
"ACE_Chemlight_UltraHiOrange",
"ACE_Chemlight_HiGreen",
"ACE_Chemlight_HiBlue",
"ACE_Chemlight_Orange",
"ACE_Chemlight_White",
"ACE_Chemlight_IR",
"ACE_Chemlight_HiWhite",
"ACE_Chemlight_HiRed",
"ACE_Chemlight_HiYellow",
"Chemlight_red",
"Chemlight_green",
"Chemlight_blue",
"Chemlight_yellow",
"ACE_M14",
"rhs_mag_an_m14_th3",
"rhs_mag_an_m8hc",
"ACE_M84",
"rhs_mag_mk84",
"rhs_mag_m7a3_cs",
"HandGrenade",
"rhs_mag_m18_green",
"rhs_mag_m18_purple",
"rhs_mag_m18_red",
"rhs_mag_m18_yellow"];

_CoItems = ["rhs_pdu4",
"UK3CB_V_Falcon_3",
"UK3CB_AAF_O_V_Eagle_GL_DIGI_GRN",
"UK3CB_AAF_O_V_Eagle_SL_DIGI_GRN",
"UK3CB_HK33KA2_RIS_GL",
"1Rnd_HE_Grenade_shell",
"UGL_FlareWhite_F",
"UGL_FlareGreen_F",
"UGL_FlareRed_F",
"UGL_FlareYellow_F",
"UGL_FlareCIR_F",
"ACE_40mm_Flare_white",
"ACE_40mm_Flare_red",
"ACE_40mm_Flare_green",
"ACE_40mm_Flare_ir",
"1Rnd_Smoke_Grenade_shell",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_SmokeGreen_Grenade_shell",
"1Rnd_SmokeYellow_Grenade_shell",
"1Rnd_SmokePurple_Grenade_shell",
"1Rnd_SmokeBlue_Grenade_shell",
"1Rnd_SmokeOrange_Grenade_shell",
"ACE_MX2A"] + _generalItems;
_FACItems = [
"ACE_MX2A",
"Laserdesignator",
"I_UAV_01_backpack_F",
"I_UavTerminal",
"CUP_LRTV",
"Laserbatteries"] + _generalItems;
_MItems = [
"UK3CB_AAF_O_V_Eagle_MED_DIGI_GRN",
"ACE_surgicalKit",
"ACE_adenosine",
"ACE_bloodIV_250",
"ACE_bloodIV",
"ACE_tourniquet",
"ACE_fieldDressing",
"ACE_morphine",
"ACE_epinephrine",
"ACE_bloodIV_500",
"ACE_quikclot",
"ACE_packingBandage",
"ACE_elasticBandage",
"ACE_personalAidKit",
"B_Kitbag_rgr"] + _generalItems;
_SLItems = [
"rhs_pdu4",
"UK3CB_V_Falcon_3",
"UK3CB_AAF_O_V_Eagle_SL_DIGI_GRN",
"UK3CB_AAF_O_V_Eagle_GL_DIGI_GRN",
"UK3CB_HK33KA2_RIS_GL",
"1Rnd_HE_Grenade_shell",
"UGL_FlareWhite_F",
"UGL_FlareGreen_F",
"UGL_FlareRed_F",
"UGL_FlareYellow_F",
"UGL_FlareCIR_F",
"1Rnd_Smoke_Grenade_shell",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_SmokeGreen_Grenade_shell",
"1Rnd_SmokeYellow_Grenade_shell",
"1Rnd_SmokePurple_Grenade_shell",
"1Rnd_SmokeBlue_Grenade_shell",
"1Rnd_SmokeOrange_Grenade_shell",
"ACE_MX2A"] + _generalItems;
_FTLItems = [
"rhs_pdu4",
"UK3CB_V_Falcon_3",
"UK3CB_AAF_O_V_Eagle_GL_DIGI_GRN",
"UK3CB_HK33KA2_RIS_GL",
"1Rnd_HE_Grenade_shell",
"UGL_FlareWhite_F",
"UGL_FlareGreen_F",
"UGL_FlareRed_F",
"UGL_FlareYellow_F",
"UGL_FlareCIR_F",
"1Rnd_Smoke_Grenade_shell",
"1Rnd_SmokeRed_Grenade_shell",
"1Rnd_SmokeGreen_Grenade_shell",
"1Rnd_SmokeYellow_Grenade_shell",
"1Rnd_SmokePurple_Grenade_shell",
"1Rnd_SmokeBlue_Grenade_shell",
"1Rnd_SmokeOrange_Grenade_shell",
"ACE_MX2A"] + _generalItems;
_RItems = [
"UK3CB_G3A3",
"rhs_weap_rpg75",
"UK3CB_MG3_50rnd_762x51_WM",
"UK3CB_MG3_50rnd_762x51_WT",
"UK3CB_MG3_100rnd_762x51_WM",
"UK3CB_MG3_100rnd_762x51_WT",
"UK3CB_MG3_250rnd_762x51_WM",
"UK3CB_MG3_250rnd_762x51_WT"] + _generalItems;
_RLATItems = [
"rhs_weap_rpg75"] + _generalItems;
_ARItems = [
"UK3CB_AAF_O_V_Eagle_MG_DIGI_GRN",
"UK3CB_MG3",
"CUP_arifle_G3A3_ris",
"CUP_arifle_G3A3_modern_ris",
"CUP_bipod_G3",
"CUP_bipod_G3SG1",
"UK3CB_G3_50rnd_762x51_WM",
"UK3CB_G3_50rnd_762x51_WT",
"UK3CB_MG3_50rnd_762x51_WM",
"UK3CB_MG3_50rnd_762x51_WT",
"UK3CB_MG3_100rnd_762x51_WM",
"UK3CB_MG3_100rnd_762x51_WT",
"UK3CB_MG3_250rnd_762x51_WM",
"UK3CB_MG3_250rnd_762x51_WT"] + _generalItems;
_ENGItems = [
"UK3CB_AAF_O_V_Eagle_EOD_DIGI_GRN",
"ACE_Clacker",
"ACE_M26_Clacker",
"ACE_DefusalKit",
"DemoCharge_Remote_Mag",
"SatchelCharge_Remote_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"APERSBoundingMine_Range_Mag",
"SLAMDirectionalMine_Wire_Mag",
"APERSMine_Range_Mag",
"APERSTripMine_Wire_Mag",
"ACE_VMH3",
"rhs_mine_ozm72_a_mag",
"rhs_mine_ozm72_b_mag",
"rhs_mine_ozm72_c_mag",
"rhs_mag_mine_pfm1",
"rhssaf_mine_pma3_mag",
"rhs_mine_msk40p_blue_mag",
"rhs_mine_msk40p_green_mag",
"rhs_mine_msk40p_red_mag",
"rhs_mine_msk40p_white_mag",
"rhs_mine_pmn2_mag",
"rhs_mag_mine_ptm1",
"CUP_PipeBomb_M",
"rhs_mine_sm320_green_mag",
"rhs_mine_sm320_red_mag",
"rhs_mine_sm320_white_mag",
"APERSMine_Range_Mag",
"ACE_LIB_LadungPM",
"APERSMineDispenser_Mag",
"DemoCharge_Remote_Mag",
"ATMine_Range_Mag",
"SatchelCharge_Remote_Mag",
"ClaymoreDirectionalMine_Remote_Mag",
"SLAMDirectionalMine_Wire_Mag",
"APERSMine_Range_Mag",
"APERSBoundingMine_Range_Mag",
"ACE_VMM3"] + _generalItems;
_MKItems = [
"rhs_pdu4",
"ACE_RangeCard",
"UK3CB_G3SG1",
"uk3cb_optic_STANAGZF_G3",
"uk3cb_optic_ZFSG1",
"uk3cb_optic_accupoint_g3",
"ACE_10Rnd_762x51_M118LR_Mag",
"ACE_20Rnd_762x51_M993_AP_Mag"] + _generalItems;
_MGItems = [
"ace_csw_staticM2ShieldCarry",
"ace_csw_m3CarryTripod",
"ace_csw_m3CarryTripodLow",
"ace_compat_rhs_usf3_mk19_carry",
"ace_csw_m3CarryTripodLow",
"ace_csw_m3CarryTripod",
"ace_csw_100Rnd_127x99_mag_yellow",
"ace_csw_100Rnd_127x99_mag",
"ace_compat_rhs_usf3_48Rnd_40mm_MK19",
"ace_compat_rhs_usf3_48Rnd_40mm_MK19_M430A1",
"ace_compat_rhs_usf3_48Rnd_40mm_MK19_M1001"] + _generalItems;
_MATItems = [
"rhs_weap_igla",
"CUP_launch_Metis",
"CUP_launch_BF3_Loaded",
"rhs_mag_9k38_rocket",
"CUP_AT13_M",
"Vorona_HEAT",
"Vorona_HE",
"CUP_PTFHC_M",
"CUP_PTFHE_M",
"CUP_PTF3IT_M"] + _generalItems;
_MTRItems = [
"RHS_Podnos_Bipod_Bag",
"ACE_1Rnd_82mm_Mo_HE",
"ACE_1Rnd_82mm_Mo_Illum",
"ACE_1Rnd_82mm_Mo_Smoke",
"RHS_Podnos_Gun_Bag"] + _generalItems;
_SPItems = [
"rhs_pdu4",
"ACE_RangeCard",
"UK3CB_PSG1A1",
"uk3cb_optic_STANAGZF_G3",
"uk3cb_optic_ZFSG1",
"uk3cb_optic_accupoint_g3",
"ACE_10Rnd_762x51_M118LR_Mag",
"ACE_20Rnd_762x51_M993_AP_Mag",
"ACE_Tripod",
"Laserdesignator",
"Laserbatteries",
"ACE_Kestrel4500",
"ACE_SpottingScope",
"20Rnd_762x51_Mag",
"rhsusf_20Rnd_762x51_m993_Mag",
"CUP_20Rnd_762x51_DMR",
"ACE_20Rnd_762x51_M118LR_Mag",
"ACE_20Rnd_762x51_Mk316_Mod_0_Mag",
"ACE_20Rnd_762x51_Mk319_Mod_0_Mag",
"CUP_bipod_VLTOR_Modpod_black",
"bipod_03_F_oli",
"CUP_bipod_Harris_1A2_L_BLK",
"ACE_20Rnd_762x51_M993_AP_Mag",
"hgun_Rook40_F",
"16Rnd_9x21_Mag",
"U_I_FullGhillie_ard",
"U_I_FullGhillie_sard",
"U_I_FullGhillie_lsh",
"optic_LRPS",
"5Rnd_127x108_Mag",
"U_I_GhillieSuit",
"5Rnd_127x108_Mag",
"5Rnd_127x108_APDS_Mag",
"rhsusf_mag_10Rnd_STD_50BMG_M33",
"rhsusf_mag_10Rnd_STD_50BMG_mk211",
"ACE_5Rnd_127x99_Mag",
"ACE_5Rnd_127x99_API_Mag",
"ACE_5Rnd_127x99_AMAX_Mag",
"CUP_10Rnd_127x99_M107"] + _generalItems;
_HPItems = [
"U_I_HeliPilotCoveralls",
"H_PilotHelmetHeli_I",
"SMG_02_F",
"SMG_03C_black",
"SMG_03C_camo",
"SMG_03C_TR_black",
"SMG_03C_TR_camo",
"SMG_01_F",
"30Rnd_45ACP_Mag_SMG_01",
"30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow",
"50Rnd_570x28_SMG_03",
"CUP_50Rnd_570x28_Yellow_Tracer_P90_M",
"30Rnd_9x21_Mag_SMG_02",
"CUP_30Rnd_9x19_EVO"] + _generalItems;
_VItems = [
"UK3CB_HK33KA3",
"UK3CB_HK33_30rnd_556x45",
"UK3CB_AAF_O_V_Eagle_CREW_DIGI_GRN",
"H_HelmetCrew_I",
"ToolKit"] + _generalItems;
_FYItems = [
"U_I_pilotCoveralls",
"H_PilotHelmetFighter_I",
"SMG_02_F",
"SMG_03C_black",
"SMG_03C_camo",
"SMG_03C_TR_black",
"SMG_03C_TR_camo",
"SMG_01_F",
"30Rnd_45ACP_Mag_SMG_01",
"30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow",
"50Rnd_570x28_SMG_03",
"CUP_50Rnd_570x28_Yellow_Tracer_P90_M",
"30Rnd_9x21_Mag_SMG_02",
"CUP_30Rnd_9x19_EVO",
"ToolKit"] + _generalItems;


_specItems = [_CoItems, _FACItems, _MItems, _SLItems, _FTLItems, _RItems, _RLATItems, _ARItems, _AARItems, _ENGItems, _MKItems, _MGItems, _MATItems, _MTRItems, _SPItems, _HPItems, _VItems, _FYItems];

//////////////////////////////////////////////////////////////////////////////////////////////

[_target, [_this select 0, _restrictionDistance, _specNames, _specSlots, _specTypes, _specItems]] spawn CHSA_fnc_executeLocalArsenal;