#include "common.sqf";

// 陣營基本道具（將會整合陣營共用道具）
private _faction_general = [
	"hlc_rifle_M27IAR",
	"rhsusf_acc_compm4",
	"USP_45L_RUCKSACK_MC",
	"rhs_mag_100Rnd_556x45_Mk262_cmag",
	"rhs_mag_100Rnd_556x45_Mk318_cmag",
	"ACE_30Rnd_556x45_Stanag_M995_AP_mag",
	"ACE_30Rnd_556x45_Stanag_Tracer_Dim",
	"rhs_weap_M136",
	"rhs_weap_M136_hedp",
	"Tier1_Glock19_Urban_TB",
	"rhsusf_acc_anpeq15_wmx_light",
	"rhsusf_acc_anpeq15_wmx",
	"GOLD_acc_BCM_GVG_tan",
	"Tier1_SIG_Romeo1",
	"Tier1_Agency_Compensator",
	"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan",
	"rhs_mag_30Rnd_556x45_M855A1_PMAG",
	"Tier1_20Rnd_9x19_FMJ",
	"USP_G3C_RS2_KP_OR_VQ_MC",
	"Crye_AVS_1",
	"Crye_AVS_1_1",
	"Crye_AVS_1_2",
	"Crye_AVS_1_3",
	"B_AssaultPack_mcamo",
	"B_Kitbag_mcamo",
	"USP_OPSCORE_FASTMTC_CMTW",
	"USP_OPSCORE_FASTMTC_TW",
	"USP_PVS31_WP_LOW",
	"USP_PVS31_WP_HIGH",
	"USP_PVS31_HIGH",
	"USP_PVS31_LOW",
	"rhs_googles_black",
	"rhs_googles_clear",
	"ItemMap",
	"ItemCompass",
	"ItemWatch",
	"ItemRadioAcreFlagged",
	"ItemGPS",
	"ToolKit",
	"ACE_DAGR",
	"ACRE_PRC117F",
	"ACRE_PRC148",
	"ACRE_PRC152",
	"ACRE_PRC343",
	"ACRE_PRC77",
	"ACE_fieldDressing",
	"ACE_bodyBag",
	"ACE_CableTie",
	"ACE_EarPlugs",
	"ACE_EntrenchingTool",
	"ACE_IR_Strobe_Item",
	"ACE_Flashlight_XL50",
	"ACE_morphine",
	"ACE_rope12",
	"ACE_rope15",
	"ACE_rope18",
	"ACE_rope27",
	"ACE_rope3",
	"ACE_rope36",
	"ACE_rope6",
	"ACE_splint",
	"ACE_tourniquet",
	"ACE_wirecutter",
	"ACE_SpareBarrel",
	"Binocular",
	"ACE_M14",
	"rhs_mag_an_m14_th3",
	"rhs_mag_an_m8hc",
	"Chemlight_blue",
	"Chemlight_green",
	"ACE_Chemlight_HiBlue",
	"ACE_Chemlight_HiGreen",
	"ACE_Chemlight_HiRed",
	"ACE_Chemlight_HiWhite",
	"ACE_Chemlight_HiYellow",
	"ACE_Chemlight_IR",
	"ACE_Chemlight_Orange",
	"Chemlight_red",
	"ACE_Chemlight_UltraHiOrange",
	"ACE_Chemlight_White",
	"Chemlight_yellow",
	"ACE_CTS9",
	"rhs_mag_mk84",
	"rhs_mag_m18_green",
	"rhs_mag_m18_purple",
	"rhs_mag_m18_red",
	"CUP_HandGrenade_M67",
	"B_IR_Grenade",
	"ACE_DAGR",
	"ACE_microDAGR",
	"ACE_MapTools",
	"ACE_HuntIR_monitor"
];

// 以 createHashMapFromArray 來建立陣營資料集並回傳
createHashMapFromArray [
	[
		// 告知這個陣營的裝備設定檔 (return by hashmap)
		"equipmentDataset",
		createHashMapFromArray [
			["general", _faction_general], // 陣營基本道具
			[
				"排長",
				[
					"GOLD_M4_Mk16_14_5_1",
					"Tier1_Razor_Gen3_110_Geissele_Docter",
					"rhsusf_acc_su230_mrds",
					"rhsusf_acc_ACOG_RMR",
					"ACE_Vector"
				]
			],
			[
				"前線火炮觀察員",
				[
					"GOLD_M4_Mk16_10_5_BCM_1",
					"Tier1_MicroT2_Black",
					"Tier1_EXPS3_0_Riser_Tano",
					"Crye_AVS_3",
					"Crye_AVS_3_1",
					"Crye_AVS_3_2",
					"Crye_AVS_3_3",
					"B_UAV_01_backpack_F",
					"ACE_UAVBattery",
					"Laserdesignator",
					"CUP_SOFLAM",
					"B_UavTerminal"
				]
			]
		]
	],
	[
		// 告知這個陣營要有那些職位 (return by array)
		"soltDataset",
		[
			[
				"排長", 99, ["B_officer_F"],
				[

					"GOLD_M4_Mk16_14_5_1",
					"Tier1_Razor_Gen3_110_Geissele_Docter",
					"rhsusf_acc_su230_mrds",
					"rhsusf_acc_ACOG_RMR",
					"ACE_Vector"
				]
			],
			[
				"前線火炮觀察員", 99, ["B_soldier_UAV_06_F"],
				[
					"GOLD_M4_Mk16_10_5_BCM_1",
					"Tier1_MicroT2_Black",
					"Tier1_EXPS3_0_Riser_Tano",
					"Crye_AVS_3",
					"Crye_AVS_3_1",
					"Crye_AVS_3_2",
					"Crye_AVS_3_3",
					"B_UAV_01_backpack_F",
					"ACE_UAVBattery",
					"Laserdesignator",
					"CUP_SOFLAM",
					"B_UavTerminal"
				]
			],
			[
				"醫護兵", 99, ["B_medic_F"],
				["GOLD_M4_Mk16_10_5_BCM_1",
					"Tier1_MicroT2_Black",
					"Tier1_EXPS3_0_Riser_Tano",
					"ACE_surgicalKit",
					"ACE_adenosine",
					"ACE_bloodIV_250",
					"ACE_bloodIV",
					"ACE_tourniquet",
					"ACE_fieldDressing",
					"ACE_morphine",
					"ACE_epinephrine",
					"ACE_bloodIV_500",
					"ACE_quikclot",
					"ACE_packingBandage",
					"ACE_elasticBandage",
					"ACE_personalAidKit"
				]
			],
			[
				"班長", 99, ["B_Soldier_SL_F"],
				[
					"GOLD_M4_Mk16_14_5_1",
					"Tier1_Razor_Gen3_110_Geissele_Docter",
					"rhsusf_acc_su230_mrds",
					"rhsusf_acc_ACOG_RMR",
					"ACE_Vector"
				]
			],
			[
				"伍長", 99, ["B_Soldier_TL_F"],
				[
					"GOLD_M4_Mk16_14_5_1",
					"Tier1_MicroT2_Black",
					"Tier1_EXPS3_0_Riser_Tano",
					"Tier1_EXPS3_0_G33_Tano_Up",
					"rhs_weap_M320",
					"rhs_mag_M441_HE",
					"rhs_mag_M433_HEDP",
					"rhs_mag_M397_HET",
					"rhs_mag_m4009",
					"rhs_mag_m576",
					"rhs_mag_m661_green",
					"rhs_mag_m662_red",
					"rhs_mag_m713_Red",
					"rhs_mag_m714_White",
					"rhs_mag_m715_Green",
					"rhs_mag_m716_yellow",
					"UGL_FlareWhite_F",
					"UGL_FlareCIR_F",
					"ACE_HuntIR_M203"
				]
			],
			[
				"步槍兵", 99, ["B_Soldier_F"],
				[
					"rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",
					"rhsusf_100Rnd_556x45_soft_pouch_ucp",
					"rhsusf_200Rnd_556x45_soft_pouch_ucp",
					"rhsusf_200Rnd_556x45_mixed_soft_pouch_ucp",
					"GOLD_M4_Mk16_10_5_BCM_1",
					"Tier1_MicroT2_Black",
					"Tier1_EXPS3_0_Riser_Tano",
					"Tier1_100Rnd_762x51_Belt_M80A1_EPR",
					"Tier1_250Rnd_762x51_Belt_M80A1_EPR",
					"MRAWS_HEAT_F",
					"MRAWS_HE_F"
				]
			],
			[
				"自動步槍兵", 99, ["B_soldier_AR_F"],
				[
					"Tier1_MK46_Mod1_Savit",
					"hlc_muzzle_OEMDevice_556",
					"rhsusf_acc_su230_mrds",
					"Tier1_Mk46Mod1_LA5_M600V_Black",
					"Tier1_SAW_Bipod_DD",
					"rhsusf_100Rnd_556x45_mixed_soft_pouch_coyote",
					"rhsusf_100Rnd_556x45_soft_pouch_ucp",
					"rhsusf_200Rnd_556x45_soft_pouch_ucp",
					"rhsusf_200Rnd_556x45_mixed_soft_pouch_ucp",
					"Crye_AVS_2"
				]
			],
			[
				"工程兵", 99, [""],
				[
					"ACE_Vector",
					"ACE_MX2A",
					"ACE_RangeCard",
					"GOLD_M4_Mk16_16_5_1",
					"Tier1_M110k5_ACS_65mm",
					"Scot_SigT6_RMR_Top",
					"Scot_VRTX_RAZR_RMR_Top",
					"Tier1_SOCOM762_2_Mini_DE",
					"rhsusf_acc_harris_bipod",
					"Tier1_Harris_Bipod_RVG_MLOK_Tan",
					"rhs_mag_30Rnd_556x45_Mk262_PMAG",
					"Tier1_20Rnd_65x48_Creedmoor_SR25_Mag",
					"ACE_20Rnd_65_Creedmor_mag"
				]
			],
			[
				"精準射手", 99, ["B_soldier_M_F"],
				[
					"CUP_lmg_Mk48_nohg",
					"rhsusf_acc_ARDEC_M240",
					"CUP_acc_ANPEQ_15_Flashlight_Black_L",
					"Tier1_Elcan_156_C2_ARD_Docter_Black",
					"CUP_optic_Elcan_SpecterDR_RMR_black",
					"rhsusf_acc_su230a_mrds",
					"Tier1_100Rnd_762x51_Belt_M80A1_EPR",
					"Tier1_250Rnd_762x51_Belt_M80A1_EPR",
					"Crye_AVS_2"
				]
			],
			[
				"排用機槍兵", 99, ["B_support_MG_F"],
				[
					"CUP_lmg_Mk48_nohg",
					"rhsusf_acc_ARDEC_M240",
					"CUP_acc_ANPEQ_15_Flashlight_Black_L",
					"Tier1_Elcan_156_C2_ARD_Docter_Black",
					"CUP_optic_Elcan_SpecterDR_RMR_black",
					"rhsusf_acc_su230a_mrds",
					"Tier1_100Rnd_762x51_Belt_M80A1_EPR",
					"Tier1_250Rnd_762x51_Belt_M80A1_EPR",
					"Crye_AVS_2"
				]
			],
			[
				"發射器專精兵", 99, ["B_soldier_AT_F"],
				[
					"GOLD_M4_Mk16_10_5_BCM_1",
					"Tier1_MicroT2_Black",
					"Tier1_EXPS3_0_Riser_Tano",
					"launch_MRAWS_green_F",
					"rhs_weap_maaws",
					"rhs_optic_maaws",
					"MRAWS_HEAT_F",
					"MRAWS_HE_F"
				]
			],
			[
				"機組員", 99, ["B_crew_F"],
				[
					"rhs_weap_m4a1_carryhandle",
					"rhsusf_weap_m9",
					"rhs_mag_30Rnd_556x45_M855A1_Stanag",
					"rhsusf_mag_15Rnd_9x19_JHP",
					"rhs_uniform_cu_ocp_1stcav",
					"rhsusf_spcs_ocp_crewman",
					"rhsusf_cvc_helmet"
				]
			],
			[
				"飛行員", 99, ["B_Pilot_F"],
				[
					"rhs_weap_m4a1_carryhandle",
					"rhsusf_weap_m9",
					"rhs_mag_30Rnd_556x45_M855A1_Stanag",
					"rhsusf_mag_15Rnd_9x19_JHP",
					"U_B_PilotCoveralls",
					"H_PilotHelmetFighter_B"
				]
			]
		]
	]
];